---
# file: group_vars/hec01.yml
idrac:
  ip: "10.178.136.254"
  mask: "255.255.254.0"
  gw: "10.178.136.1"
  name: "naa-hec10-idrac-01"
  dns1: "147.204.148.110"
  dns2: "147.204.148.111"
  domain: "net.sap.corp"
  password: "arista"

cva:
# attention not .43 :
  ip: "10.178.136.41"
  mask: "255.255.254.0"
  gw: "10.178.136.1"
  name: "naa-hec01-01"
  dns1: "147.204.148.110"
  dns2: "147.204.148.111"
  domain: "net.sap.corp"
  password: "arista"

oob2 and oob3:
  dhcp:
    prefix: "10.178.136.0"
    mask: "255.255.254.0"
    router: "10.178.136.1"
    idrac_ip: "10.178.137.248"
    cva_ip: "10.178.137.249"

cvp:
  # there is already 1.3 on arista web page
  version: "cvp-2019.1.2-kvm.tgz"
  # path to be checked
  path_to_cvp_file: "/ens/bin/images/arista/"
  ip_eth0: "10.178.137.253"
  ip_eth1: "10.255.241.69"
  mask_eth0: "255.255.254.0"
  mask_eth1: "255.255.240.0"
  gw: "10.178.136.1"
  name: "naa-hec01-cvp-01.net.sap.corp"
  dns1: "10.17.121.30"
  dns2: "10.17.122.10"
  domain: "net.sap.corp"
  ntp1: "10.17.122.185"
  ntp2: "10.33.142.104"
  device_int: eth0
  cluster_int: eth1
  ingest_key: "SecureKey01"
  vmname: "cvp-hec01"
  KvmDomain: "cvp"
  password: "arista"
  backupuser: "cvpbkp"
  eth1_routes:
  # HEC01-NW-MGMT-04 (all router and ipmis)
    - prefix: "198.19.234.0"
      mask: "24"
      nexthop: "10.255.241.78"
  # HEC01-NW-MGMT05 (all fab)
    - prefix: "198.19.190.0"
      mask: "24"
      nexthop: "10.255.241.78"
  dhcp:
    prefix: "10.178.140.0"
    mask: "255.255.254.0"
    range_low: "10.178.137.224"
    range_high: "10.178.137.247"
  aaa_config:
    aaa_type: "RADIUS"
    servers:
      - ip: "10.17.121.35"
        secret: "secretRadPw"
        authMode: "PAP"
        authPort: 1645
        accPort: 1646
        status: "Enabled"
      - ip: "10.17.122.21"
        secret: "secretRadPw"
        authMode: "PAP"
        authPort: 1645
        accPort: 1646
        status: "Enabled"
hec:
  hec_nr: "02"
  hana_hvx_descriptions_PO_MIN: 101
  hana_hvx_descriptions_PO_MAX: 124
  hvv_descriptions_PO_MAX: 24
  hvv_descriptions_PO_RANGE: "{101,151}"
  ma_domain: "net.sap.corp"
  lo900_domain: "ams.hec.sap.biz"
  vl900_domain: "ams.hec.sap.biz"
  vl900_mask: 24
  vl900_def_gw: 198.19.241.1
  vl900_net: 198.19.241.0/24
  lo900_net: 198.19.195.0/24
  lo900_prefix: 198.19.195
  inband_trans_brdr: 10.255.252.78
  inband_trans_net: 10.255.252.64/28
  inband_trans_prefix: 10.255.252
  inband_trans_mask: 28
  inband_trans_gw_vlan: Vlan916
  inband_trans_gw: 10.255.252.65
  inband_trans_cvx: 10.255.252.68
  inband_trans_cvp: 10.255.252.69
  oob_def_gw: 10.178.140.1
  oob_prefix: 10.178.140
  oob_mask: 23
  oob_cvx: 10.178.141.252
  oob_cvp: 10.178.141.253
  as_low: 4200998673
  as_high: 4200999871
  cvp_ingest_key: SecureKey02
  dns1: 10.127.141.1
  dns2: 10.127.141.2
  ntp1: 147.204.148.93
  ntp2: 147.204.148.92
  syslog1: 147.204.132.91
  syslog2: 147.204.133.69
  syslog3: 147.204.146.42
  radius1: 10.17.122.21
  radius2: 10.17.121.35
  admin_mpls:
    - prefix_mask: "10.178.140.0/23"
      sequence: "20"
  admin_sw_interface: Ethernet49
  admin_sw_description_oob1a: "amsdc02-adm-01-co Gi1/1/1"
  admin_sw_description_oob1b: "amsdc02-adm-02-co Gi1/1/1"
  admin_sw_prefix: 10.255.202
  admin_sw_mask: 29
  admin_sw_ip_oob1a: 10.255.202.9
  admin_sw_ip_oob1b: 10.255.202.10
  admin_sw_neig_ip_oob1a: 10.255.202.11
  admin_sw_neig_as_oob1a: 1.463
  admin_sw_neig_ip_oob1b: 10.255.202.12
  admin_sw_neig_as_oob1b: 1.463
  oob01_lo0_prefix: 198.19.249
  oob01_as: 64531.2
  spine_nr:
    - 11
    - 12
    - 13
    - 14
  oob01a_snmp_contact: 34368082:ncons-hec02-06.net.sap.corp:1015
  oob01a_snmp_location: NL-AMS-AM7-Z1C-02-01-39
  oob01b_snmp_contact: 34368083:ncons-hec02-07.net.sap.corp:1015
  oob01b_snmp_location: NL-AMS-AM7-Z1C-03-01-39
  oobs_2_7:
    - number: 02
      snmp_contact: 34340574:ncons-hec02-06.net.sap.corp:1016
      snmp_location: EMEA-Netherlands-Amsterdam-Amsterdam7(AM6)-Cage2(Z1C)-02-01-38
      ip_last_octett: 4
    - number: 03
      snmp_contact: 34340566:ncons-hec02-07.net.sap.corp:1017
      snmp_location: EMEA-Netherlands-Amsterdam-Amsterdam7(AM6)-Cage2(Z1C)-03-01-38
      ip_last_octett: 5
    - number: 04
      snmp_contact: 34340569:ncons-hec02-08.net.sap.corp:1001
      snmp_location:  EMEA-Netherlands-Amsterdam-Amsterdam7(AM6)-Cage2(Z3E)-02-07-32
      ip_last_octett: 6
    - number: 05
      snmp_contact: unknown
      snmp_location: unknown
      ip_last_octett: 7
    - number: 06
      snmp_contact: unknown
      snmp_location: unknown
      ip_last_octett: 8
  hvv_hvx_acl_rules: |
      10 permit vlan 50 0x000 icmp any any
      20 permit vlan 50 0x000 pim any any
      30 permit vlan 50 0x000 92 any any
      40 permit vlan 50 0x000 vrrp any any
      50 permit vlan 50 0x000 ip any 224.0.0.0/5
      60 permit vlan 50 0x000 ip 198.18.48.0/22 host 198.18.51.255
      70 permit vlan 50 0x000 ip 198.18.48.0/22 198.18.51.0/24
      80 permit vlan 50 0x000 ip 198.18.51.0/24 198.18.48.0/22
      90 permit vlan 50 0x000 ip 198.18.48.0/22 host 198.18.48.1
      100 deny vlan 50 0x000 ip 198.18.48.0/22 198.18.48.0/22 log
      110 permit vlan 50 0x000 ip 198.18.48.0/22 any
      120 permit vlan 50 0x000 ip any any log
      130 permit vlan 60 0x000 icmp any any
      140 permit vlan 60 0x000 pim any any
      150 permit vlan 60 0x000 92 any any
      160 permit vlan 60 0x000 vrrp any any
      170 permit vlan 60 0x000 ip any 224.0.0.0/5
      180 permit vlan 60 0x000 ip 198.18.52.0/22 host 198.18.52.1
      190 permit vlan 60 0x000 ip 198.18.52.0/22 host 198.18.55.255
      200 deny vlan 60 0x000 ip 198.18.52.0/22 198.18.52.0/22 log
      210 permit vlan 60 0x000 ip 198.18.52.0/22 any
      220 permit vlan 60 0x000 ip 198.18.56.0/22 host 198.18.59.255
      230 permit vlan 60 0x000 ip 198.18.56.0/22 host 198.18.56.1
      240 deny vlan 60 0x000 ip 198.18.56.0/22 198.18.56.0/22 log
      250 permit vlan 60 0x000 ip 198.18.56.0/22 any
      260 permit vlan 60 0x000 ip any any log
      270 permit ip any any
  hana_acl_rules: |
      10 permit icmp any any
      20 permit pim any any
      30 permit 92 any any
      40 permit vrrp any any
      50 permit ip any 224.0.0.0/5
      60 permit ip 198.18.40.0/23 host 198.18.41.255
      70 permit ip 198.18.40.0/23 host 198.18.40.4
      80 permit ip host 198.18.40.4 198.18.40.0/23
      90 permit ip 198.18.40.0/23 host 198.18.40.6
      100 permit ip host 198.18.40.6 198.18.40.0/23
      110 permit ip 198.18.40.0/23 198.18.41.192/26
      120 permit ip 198.18.41.192/26 198.18.40.0/23
      130 permit ip 198.18.40.0/23 host 198.18.40.1
      140 deny ip 198.18.40.0/23 198.18.40.0/23
      150 permit ip 198.18.40.0/23 any
      160 permit ip any any
  snmp_acl: |
    ip access-list standard ACL_SNMP_VTY
       10 permit host 10.17.53.58
       20 permit host 10.17.53.57
       30 permit host 10.17.47.44
       40 permit host 169.145.33.36
       50 permit host 169.145.33.160
       60 permit host 169.145.84.136
       70 permit host 147.204.148.20
       80 permit host 147.204.148.87
       90 permit host 147.204.148.100
       100 permit host 147.204.148.101
       110 permit host 147.204.148.156
       120 permit host 194.39.131.37
       130 permit 10.18.117.0/24
       140 permit 10.21.104.0/24
       150 permit 10.23.111.0/24
       160 permit 10.17.120.0 0.0.252.255
       170 permit 10.17.158.0 0.0.254.255
       180 permit 10.17.160.0 0.0.252.255
       190 permit 147.204.128.0/25
       200 permit 147.204.144.0/25
       210 permit 169.145.80.0/25
       220 permit 169.145.104.0/25
       230 permit 169.145.152.0/25
       240 permit 169.145.208.0/25
       250 permit 169.145.216.0/25
       260 permit 169.145.240.0/25
       270 permit 169.145.248.0/25
       280 permit 100.127.0.0/25
       290 permit 100.127.8.0/25
       300 permit 100.127.16.0/25
       310 permit 100.127.32.0/25
       320 permit 147.204.128.32/31
       330 permit 147.204.146.32/31
       340 permit 147.204.149.224/30
       350 permit host 147.204.149.87
       360 permit 169.145.80.32/31
       370 permit 169.145.104.32/31
       380 permit 169.145.152.32/31
       390 permit 169.145.208.32/31
       400 permit 169.145.216.32/31
       410 permit 169.145.240.32/31
       420 permit 169.145.248.32/31
       430 permit host 169.145.82.6
       440 permit host 169.145.106.32
       450 permit host 169.145.106.33
       460 permit host 169.145.220.74
       470 permit 100.127.0.32/31
       480 permit 100.127.8.32/31
       490 permit 100.127.16.32/31
       500 permit 100.127.32.32/31
       510 permit 169.145.33.64/26
       520 permit 198.19.224.0/19
       530 permit 198.19.166.0/24
       540 permit 198.19.167.0/24
       550 permit 198.19.170.0/24
       560 permit 198.19.171.0/24
       570 permit 198.19.190.0/24
       580 permit 198.19.191.0/25
       590 permit 198.19.194.0/24
       600 permit 198.19.195.0/24
       610 permit 198.19.200.0/24
       620 permit 198.19.201.0/24
       630 permit 198.19.202.0/24
       640 permit 198.19.203.0/24
       650 permit 198.19.204.0/24
       660 permit 198.19.206.0/24
       670 permit 198.19.207.0/24
       680 deny any
    !

container:
  - name: "Fabric"
    is_root: "yes"
    subcontainer:
    - name: "HEC01"
      below_root: "yes"
      configlets:
        - name: "sw-hec01"
        - name: "sw-hec01-aaa"
        - name: "CVP-Arista"
      subcontainer:
        - name: "HEC01-IPMI"
          configlets:
            - name: "HEC01-IPMI"
            - name: "mgmt-oob"
            - name: "sw-hec01-oob-vrf"
            - name: "sw-hec01-tele-oob"
            - name: "sw-hec01-autoconf-ipmi"
        - name: "HEC01-Out of band"
          configlets:
            - name: "mgmt-default"
            - name: "sw-hec01-oob-common"
            - name: "sw-hec01-oob-vrf"
            - name: "sw-hec01-tele-default"
        - name: "HEC01-External Connectivity"
        - name: "HEC01-CWAN"
        - name: "HEC01-FWT"
        - name: "HEC01-InterDC"
        - name: "HEC01-Backup Routers"
        - name: "HEC01-Switched Fabric"
          configlets:
            - name: "HEC01-VLANs"
          subcontainer:
            - name: "HEC01-Core"
            - name: "HEC01-Top of rack"
        - name: "HEC01-Routed Fabric"
          configlets:
            - name: "CVP-Arista"
            - name: "sw-hec01-fab-L900"
            - name: "sw-hec01-oob-vrf"
            - name: "sw-hec01-tele-oob"
            - name: "mgmt-default"
          subcontainer:
            - name: "HEC01-Spine"
              configlets:
                - name: "sw-hec01-spine"
            - name: "HEC01-Special leaf"
            - name: "HEC01-Service leaf"
            - name: "HEC01-NGDR"
            - name: "HEC01-Leaf"
              configlets:
                - name: "sw-hec01-leaf"
              subcontainer:
                - name: "HEC01-HANA leaf"
                  configlets:
                    - name: "hec01-hana"
                    - name: "sw-hec01-autoconf"
                    - name: "sw-hec01-descriptions"
                - name: "HEC01-HV leaf"
                  configlets:
                    - name: "HEC01-VLANs"
                    - name: "sw-hec01-autoconf"
                - name: "HEC01-VMWare leaf"
                  configlets:
                    - name: "hec01-vmware"
                    - name: "sw-hec01-descriptions-hvv"
                - name: "HEC01-Xen leaf"
                  configlets:
                    - name: "hec01-xen"
                    - name: "sw-hec01-descriptions"
    - name: "HEC01-Unmanaged"
      below_root: "yes"
