---
# file: group_vars/hec04.yml
idrac:
  ip: "10.9.243.254"
  mask: "255.255.254.0"
  gw: "10.9.242.1"
  name: "naa-hec04-idrac-01"
  dns1: "169.145.109.5"
  dns2: "169.145.109.6"
  domain: "net.sap.corp"
  password: "arista"

cva:
  ip: "10.9.242.39"
  mask: "255.255.254.0"
  gw: "10.9.242.1"
  name: "naa-hec04-01"
  dns1: "169.145.109.5"
  dns2: "169.145.109.6"
  domain: "net.sap.corp"
  password: "arista"

oob01:
  dhcp:
    prefix: "10.9.242.0"
    mask: "255.255.254.0"
    router: "10.9.242.1"
    idrac_ip: "10.9.243.254"
    cva_ip: "10.9.242.39"

cvp:
  version: cvp-2019.1.2-kvm.tar
  path_to_cvp_file: /ens/bin/images/arista/
  # out of band ip for cvp :
  ip_eth0: 10.9.243.253
  mask_eth0: 255.255.254.0
  gw: 10.9.242.1
  # inband transport ip for cvp (for configuration purpose) VLAN920
  ip_eth1: 10.255.177.69
  mask_eth1: 255.255.255.240
  name: naa-hec04-cvp-01.net.sap.corp
  # nsq-dns-01 and dns-02 :
  dns1: 10.4.202.200
  dns2: 10.4.12.200
  domain: net.sap.corp
  ntp1: 10.4.12.100
  ntp2: 10.4.12.102
  device_int: eth0
  cluster_int: eth1
  ingest_key: SecureKey04
  vmname: cvp-hec04
  KvmDomain: cvp
  password: arista
  backupuser: cvpbkp
  eth1_routes:
      # IPMI NW Mgmt Range (HEC04-NW-MGMT07)
    - prefix: 198.19.202.0
      mask: 23
      nexthop: 10.255.177.78
      # Leaf and Spine NW Mgmt Range (HEC04-NW-MGMT08)
    - prefix: 198.19.158.0
      mask: 23
      nexthop: 10.255.177.78  
  dhcp:
    prefix: 10.9.242.0
    mask: 255.255.254.0
    range_low: 10.9.243.224
    range_high: 10.9.243.247
  aaa_config:
    aaa_type: RADIUS
    servers:
      - ip: 10.4.201.55
        secret: secretRadPw
        authMode: PAP
        authPort: 1645
        accPort: 1646
        status: Enabled
      - ip: 169.145.33.70
        secret: secretRadPw
        authMode: PAP
        authPort: 1645
        accPort: 1646
        status: Enabled

hec:
  hec_nr: "04"
  hana_hvx_descriptions_PO_MIN: 101
  hana_hvx_descriptions_PO_MAX: 124
  hvv_descriptions_PO_MAX: 24
  hvv_descriptions_PO_RANGE: "{101,151}"
  ma_domain: "net.sap.corp"
  lo900_domain: "sac.hec.sap.biz"
  vl900_domain: "sac.hec.sap.biz"
  vl900_mask: 24
  vl900_def_gw: 198.19.241.1
  vl900_net: 198.19.243.0/24
  lo900_net: 198.19.158.0/ 24
  lo900_prefix: 198.19.158
  inband_trans_brdr: 10.255.177.78
  inband_trans_net: 10.255.177.64/28
  inband_trans_prefix: 10.255.177
  inband_trans_mask: 28
  inband_trans_gw_vlan: Vlan916
  inband_trans_gw: 10.255.177.65
  inband_trans_cvx: 10.255.177.68
  inband_trans_cvp: 10.255.177.69
  oob_def_gw: 10.9.242.1
  oob_prefix: 10.9.242
  oob_mask: 23
  oob_cvx: 10.9.243.252
  oob_cvp: 10.9.243.253
  as_low: 4200998673
  as_high: 4200999871
  cvp_ingest_key: SecureKey04
  dns1: 169.145.109.5
  dns2: 169.145.109.6
  ntp1: 169.145.108.9
  ntp2: 169.145.108.10
  syslog1: 169.145.33.24
  syslog2: 169.145.109.69
  syslog3: 169.145.84.91
  radius1: 10.4.201.55
  radius2: 169.145.33.70
  admin_mpls:
    - prefix_mask: "10.9.242.0/23"
      sequence: "20"
  admin_sw_interface: Ethernet49
  admin_sw_description_oob1a: "sjcdc01-adm-03-co eth1/13"
  admin_sw_description_oob1b: "sjcdc01-adm-04-co eth1/13"
  admin_sw_prefix: 10.255.192
  admin_sw_mask: 31
  admin_sw_ip_oob1a: 10.255.202.8
  admin_sw_ip_oob1b: 10.255.202.10
  admin_sw_neig_ip_oob1a: 10.255.192.9
  admin_sw_neig_as_oob1a: 65999
  admin_sw_neig_ip_oob1b: 10.255.192.11
  admin_sw_neig_as_oob1b: 64536
  oob01_lo0_prefix: 198.19.249
  oob01_as: 4229103620
  spine_nr:
    - 11
    - 12
    - 13
    - 14
  spine:
    # valid models are: 7504, 7508, 7280
    model: 7504
    # number of linecards if spine is modular switch
    # if spine model is fixed chassis then linecards needs to have value of '1'
    linecards: 4
    fortygig:
      - 3/1/1
      - 3/2/1
      - 3/13/1
      - 3/l4/1
    number:
      - id: 11
        snmp:
          location: US-CA01-P30-C46-U3
          contact: 34412895:ncons-hec04-oob-01.net 1007
      - id: 12
        snmp:
          location: US-CA01-P30-C47-U3
          contact: 34412896:ncons-hec04-oob-01.net 1008
      - id: 13
        snmp:
          location: US-CA01-P30-C48-U3
          contact: 34412897:ncons-hec04-oob-01.net 1009
      - id: 14
        snmp:
          location: US-CA01-P30-C49-U3
          contact: 34412898:ncons-hec04-oob-01.net 1010
  fabric:
    # valid modes are: manual, cvx, evpn, manual
    vtep_distribution_mode: manual
    vtep_ips:
      - 10.200.1.1
      - 10.200.1.2
      - 10.200.1.3
      - 10.200.1.4
      - 10.200.1.5
      - 10.200.1.6
      - 10.200.1.7
      - 10.200.1.8
    interlink_mtu: 9214
    # valid speeds are 40gfull, 100gfull
    interlink_speed: 100gfull
    bgp_maximum_routes: 12000
  oob01a_snmp_contact: xxxxxx:ncons-hec04-oob-01:1002
  oob01a_snmp_location: CA01-P30-C50-U39
  oob01b_snmp_contact: xxxxxx:ncons-hec04-oob-01:1003
  oob01b_snmp_location: CA01-P30-C50-U38
  oobs_2_7:
    - number: 02
      snmp_contact: xxxxxx:ncons-hec04-oob-01:1001
      snmp_location: CA01-POD30-C50-RU43
      ip_last_octett: 22
  hvv_hvx_acl_rules: |
      10 permit vlan 50 0x000 icmp any any
      20 permit vlan 50 0x000 pim any any
      30 permit vlan 50 0x000 92 any any
      40 permit vlan 50 0x000 vrrp any any
      50 permit vlan 50 0x000 ip any 224.0.0.0/5
      60 permit vlan 50 0x000 ip 198.18.48.0/22 host 198.18.51.255
      70 permit vlan 50 0x000 ip 198.18.48.0/22 198.18.51.0/24
      80 permit vlan 50 0x000 ip 198.18.51.0/24 198.18.48.0/22
      90 permit vlan 50 0x000 ip 198.18.48.0/22 host 198.18.48.1
      100 deny vlan 50 0x000 ip 198.18.48.0/22 198.18.48.0/22 log
      110 permit vlan 50 0x000 ip 198.18.48.0/22 any
      120 permit vlan 50 0x000 ip any any log
      130 permit vlan 60 0x000 icmp any any
      140 permit vlan 60 0x000 pim any any
      150 permit vlan 60 0x000 92 any any
      160 permit vlan 60 0x000 vrrp any any
      170 permit vlan 60 0x000 ip any 224.0.0.0/5
      180 permit vlan 60 0x000 ip 198.18.52.0/22 host 198.18.52.1
      190 permit vlan 60 0x000 ip 198.18.52.0/22 host 198.18.55.255
      200 deny vlan 60 0x000 ip 198.18.52.0/22 198.18.52.0/22 log
      210 permit vlan 60 0x000 ip 198.18.52.0/22 any
      220 permit vlan 60 0x000 ip 198.18.56.0/22 host 198.18.59.255
      230 permit vlan 60 0x000 ip 198.18.56.0/22 host 198.18.56.1
      240 deny vlan 60 0x000 ip 198.18.56.0/22 198.18.56.0/22 log
      250 permit vlan 60 0x000 ip 198.18.56.0/22 any
      260 permit vlan 60 0x000 ip any any log
      270 permit ip any any
  hana_acl_rules: |
      10 permit icmp any any
      20 permit pim any any
      30 permit 92 any any
      40 permit vrrp any any
      50 permit ip any 224.0.0.0/5
      60 permit ip 198.18.40.0/23 host 198.18.41.255
      70 permit ip 198.18.40.0/23 host 198.18.40.4
      80 permit ip host 198.18.40.4 198.18.40.0/23
      90 permit ip 198.18.40.0/23 host 198.18.40.6
      100 permit ip host 198.18.40.6 198.18.40.0/23
      110 permit ip 198.18.40.0/23 198.18.41.192/26
      120 permit ip 198.18.41.192/26 198.18.40.0/23
      130 permit ip 198.18.40.0/23 host 198.18.40.1
      140 deny ip 198.18.40.0/23 198.18.40.0/23
      150 permit ip 198.18.40.0/23 any
      160 permit ip any any
