---
# file: group_vars/hec02.yml
idrac:
  ip: "10.178.141.254"
  mask: "255.255.254.0"
  gw: "10.178.140.1"
  name: "naa-hec02-idrac-01"
  dns1: "100.127.141.1"
  dns2: "100.127.141.2"
  domain: "net.sap.corp"
  password: "arista"

cva:
  ip: "10.178.140.43"
  mask: "255.255.254.0"
  gw: "10.178.140.1"
  name: "naa-hec02-01"
  dns1: "100.127.141.1"
  dns2: "100.127.141.2"
  domain: "net.sap.corp"
  password: "arista"

oob01:
  dhcp:
    prefix: "10.178.140.0"
    mask: "255.255.254.0"
    router: "10.178.140.1"
    idrac_ip: "10.178.141.248"
    cva_ip: "10.178.141.249"

cvp:
  version: "cvp-2018.2.4-kvm.tgz"
  path_to_cvp_file: "/ens/bin/images/arista/"
  ip_eth0: "10.178.141.253"
  ip_eth1: "10.255.252.69"
  mask_eth0: "255.255.254.0"
  mask_eth1: "255.255.240.0"
  gw: "10.178.140.1"
  name: "naa-hec02-cvp-01.net.sap.corp"
  dns1: "10.17.121.30"
  dns2: "10.17.122.10"
  domain: "net.sap.corp"
  ntp1: "10.17.122.185"
  ntp2: "10.4.12.100"
  device_int: eth0
  cluster_int: eth1
  ingest_key: "SecureKey02"
  vmname: "cvp-hec02"
  KvmDomain: "cvp"
  password: "arista"
  backupuser: "cvpbkp"
  eth1_routes:
    - prefix: "198.19.241.0"
      mask: "24"
      nexthop: "10.255.252.78"
    - prefix: "198.19.195.0"
      mask: "24"
      nexthop: "10.255.252.78"
  dhcp:
    prefix: "10.178.140.0"
    mask: "255.255.254.0"
    range_low: "10.178.141.224"
    range_high: "10.178.141.247"
  aaa_config:
    aaa_type: "RADIUS"
    servers:
      - ip: "10.17.121.35"
        secret: "secretRadPw"
        authMode: "PAP"
        authPort: 1645
        accPort: 1646
        status: "Enabled"
      - ip: "10.17.122.21"
        secret: "secretRadPw"
        authMode: "PAP"
        authPort: 1645
        accPort: 1646
        status: "Enabled"
