---
# file: group_vars/hec14.yml
idrac:
 ip: "10.9.247.254"
 mask: "255.255.254.0"
 gw: "10.9.246.1"
 name: "naa-hec14-01-idrac"
 # dns not required but set to the landscape dns1 and dns2 reserved in TIC HEC14-CIS01-DNS01:
 dns1: "100.127.45.1"
 dns2: "100.127.45.2"
 domain: "net.sap.corp"
 password: "arista"


cva:
 ip: "10.9.246.20"
 mask: "255.255.254.0"
 gw: "10.9.246.1"
 name: "naa-hec14-01"
 dns1: "100.127.45.1"
 dns2: "100.127.45.2"
 domain: "net.sap.corp"
 password: "arista"


oob01:
  dhcp:
    prefix: "10.9.246.0"
    mask: "255.255.254.0"
    router: "10.9.246.1"
    idrac_ip: "10.9.247.248"
    cva_ip: "10.9.247.249"

cvp:
  version: "cvp-2019.1.2-kvm.tar"
  path_to_cvp_file: "/ens/bin/images/arista/"
  # out of band ip for cvp :
  ip_eth0: "10.9.247.253"
  # inband transport ip for cvp (for configuration purpose)
  ip_eth1: "10.255.186.69"
  mask_eth0: "255.255.254.0"
  mask_eth1: "255.255.255.240"
  gw: "10.9.246.1"
  name: "naa-hec14-cvp-01.net.sap.corp"
  # nsq-dns-01 and dns-02 :
  dns1: "10.4.202.200"
  dns2: "10.4.12.200"
  domain: "net.sap.corp"
  ntp1: "10.4.12.100"
  ntp2: "10.4.12.102"
  device_int: eth0
  cluster_int: eth1
  ingest_key: "SecureKey14"
  vmname: "cvp-hec14"
  KvmDomain: "cvp"
  password: "arista"
  backupuser: "cvpbkp"
  eth1_routes:
      # IPMI NW Mgmt Range (HEC14-NW-MGMT01)
    - prefix: "198.19.233.0"
      mask: "25"
      nexthop: "10.255.186.78"
      # Leaf and Spine NW Mgmt Range (Lo900)
    - prefix: "198.19.182.0"
      mask: "24"
      nexthop: "10.255.186.78"

dhcp:
  prefix: "10.9.246.0"
  mask: "255.255.254.0"
  range_low: "10.9.247.224"
  range_high: "10.9.247.247"
aaa_config:
  aaa_type: "RADIUS"
  servers:
    - ip: "169.145.33.70"
      secret: ""
      authMode: "PAP"
      authPort: 1645
      accPort: 1646
      status: "Enabled"
    - ip: "10.4.201.55"
      secret: ""
      authMode: "PAP"
      authPort: 1645
      accPort: 1646
      status: "Enabled"

hec:
  hec_nr: "14"
  hana_hvx_descriptions_PO_MIN: 101
  hana_hvx_descriptions_PO_MAX: 124
  hvv_descriptions_PO_MAX: 24
  hvv_descriptions_PO_RANGE: "{101,151}"
  ma_domain: "net.sap.corp"
  lo900_domain: "tor2.hec.sap.biz"
  vl900_domain: "tor2.hec.sap.biz"
  vl900_mask: 25
  vl900_def_gw: 198.19.233.1
  vl900_net: 198.19.233.0/25
  lo900_net: 198.19.182.0/24
  lo900_prefix: 198.19.182
  inband_trans_brdr: 10.255.186.78
  inband_trans_brdr_mac: 00:1c:73:00:00:96
  inband_trans_net: 10.255.186.64/28
  inband_trans_prefix: 10.255.186
  inband_trans_mask: 28
  inband_trans_gw_vlan: Vlan916
  inband_trans_gw: 10.255.186.65
  inband_trans_cvx: 10.255.186.68
  inband_trans_cvp: 10.255.186.69
  oob_def_gw: 10.9.246.1
  oob_prefix: 10.9.246
  oob_mask: 23
  oob_vrf: OOB
  oob_cvx: 10.9.246.252
  oob_cvp: 10.9.246.253
  as_low: 4200998673
  as_high: 4200999871
  cvp_ingest_key: SecureKey02
  dns1: 100.127.45.1
  dns2: 100.127.45.2
  ntp1: 169.145.84.7
  ntp2: 169.145.84.11
  snmp1: 147.204.148.100
  snmp2: 147.204.148.87
  syslog1: 169.145.33.24
  syslog2: 169.145.84.91
  syslog3: 100.127.45.6
  radius1: 10.4.201.55
  radius2: 169.145.33.70
  admin_mpls:
    - prefix_mask: "10.9.246.0/23"
      sequence: "20"
  admin_sw_interface: Ethernet1
  admin_sw_description_oob1a: "tordc02-adm-03-co Ethernet1/13"
  admin_sw_description_oob1b: "tordc02-adm-04-co Ethernet1/13"
  admin_sw_prefix: 10.255.195
  admin_sw_mask: 31
  admin_sw_ip_oob1a: 10.255.195.8
  admin_sw_ip_oob1b: 10.255.195.10
  admin_sw_neig_ip_oob1a: 10.255.195.9 
  admin_sw_neig_as_oob1a: 1.463
  admin_sw_neig_ip_oob1b: 10.255.195.11
  admin_sw_neig_as_oob1b: 64536
  oob01_lo0_prefix: 198.19.249
  oob01_as: 64531.14
  spine_nr:
    - 11
    - 12
    - 13
    - 14
  spine:
    # valid models are: 7504, 7508, 7280
    model: 7504
    # number of linecards if spine is modular switch
    # if spine model is fixed chassis then linecards needs to have value of '1'
    linecards: 2
    underlay_bfd: True
  fabric:
    # valid modes are: manual, cvx, evpn, manual
    vtep_distribution_mode: evpn
    interlink_mtu: 9214
    # valid speeds are 40gfull, 100gfull
    interlink_speed: 100gfull
    bgp_maximum_routes: 12000
    evpn_maximum_routes: 0
    #Are the core vlans 3000 to 3599 needed 
    evpn_core_vlan: true
    mlag_a_ip: 198.19.224.1
    mlag_b_ip: 198.19.224.2
    leaf_models:
      - model: 7160-32CQ
        uplink_ports: 29/1,30/1,31/1,32/1
      - model: 7160-48YC6
        uplink_ports: 51/1,52/1,53/1,54/1
      - model: 7280QR-C36
        uplink_ports: 25/1,26/1,35/1,36/1
      - model: 7280SR-48C6
        uplink_ports: 51/1,52/1,53/1,54/1
    ngdr:
      edge_as: 65194
  oob01a_snmp_contact: ncons-hec14-oob-02.net.sap.corp:1005
  oob01a_snmp_location: CA-TOR2-CAGE3-CAB40-U43
  oob01b_snmp_contact: ncons-hec14-oob-02.net.sap.corp:1006
  oob01b_snmp_location: CA-TOR2-CAGE3-CAB40-U43
  oobs_2_7:
    - number: 02
      snmp_contact: ncons-hec14-oob-01:1001
      snmp_location: CA-TOR2-CAGE3-CAB40-U44
      ip_last_octett: 4
    - number: 03
      snmp_contact: ncons-hec14-oob-03:1009
      snmp_location: CA-TOR2-CAGE3-CAB44-U41
      ip_last_octett: 5
    - number: 04
      snmp_contact: unknown
      snmp_location:  unknown
      ip_last_octett: 6
    - number: 05
      snmp_contact: unknown
      snmp_location: unknown
      ip_last_octett: 7
    - number: 06
      snmp_contact: unknown
      snmp_location: unknown
      ip_last_octett: 8
  brdr:
    - number: 1a
      uplinks:
        - 29
        - 30
        - 31
        - 32
      uplinks_speed: 100gfull
      snmp:
        contact: 34672182:ncons-hec14-oob-01.net 1002
        location: CA-TOR2-CAGE3-CAB40-U41
      lo900_suffix: 41
      mgmt1_suffix: 21
      spine_port_towards_leaf: Et3/3/1
      ports:
        - id: 961
          type: vlan
          description: Transfer to rt-hec14-cwan-01a
          mtu: 9100
          ip: 10.254.253.1/31
          ngdr_underlay: true
          ngdr_underlay_neighbor: 10.254.253.0
        - id: 965
          type: vlan
          description: Transfer to rt-hec14-vpn-01a
          mtu: 9100
          ip: 10.254.253.9/31
          ngdr_underlay: true
          ngdr_underlay_neighbor: 10.254.253.8
        - id: 1
          description: rt-hec14-core-01a, Fo0/2/0
          po: 1101
          speed: 40gfull
        - id: 2
          description: rt-hec14-core-01b, Fo0/2/0
          po: 1102
          speed: 40gfull
        - id: 3
          description: rt-hec14-cwan-01a, Fo0/0/0
          po: 1103
          speed: 40gfull
        - id: 4
          description: rt-hec14-idc-01a, Fo0/0/0
          po: 1104 
          speed: 40gfull
        - id: 27
          description: sw-hec14-brdr-01b, Et27
          po: 42
        - id: 28
          description: sw-hec14-brdr-01b, Et28
          po: 42
        - id: 5
          description: rt-hec14-vpn-01a
          po: 1106
          speed: 40gfull
        - id: 6
          description: rt-hec14-inet-01a
          po: 1105
          speed: 40gfull
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 1101
          description: rt-hec14-core-01a
          trunk: all
        - id: 1102
          description: rt-hec14-core-01b
          trunk: all
        - id: 1103
          description: rt-hec14-cwan-01a
          trunk: all
        - id: 1104
          description: rt-hec14-idc-01a
          trunk: all         
        - id: 1105
          description: rt-hec14-inet-01a
          trunk: all  
        - id: 1106
          description: rt-hec14-vpn-01a
          trunk: all       
    - number: 1b
      uplinks:
        - 29
        - 30
        - 31
        - 32
      uplinks_speed: 100gfull
      snmp:
        contact: 34672183:ncons-hec14-oob-01.net 1003
        location: CA-TOR2-CAGE3-CAB40-U39
      lo900_suffix: 42
      mgmt1_suffix: 22
      spine_port_towards_leaf: Et3/4/1
      ports:
        - id: 962
          type: vlan
          description: Transfer to rt-hec14-cwan-01a
          mtu: 9100
          ip: 10.254.253.3/31
          ngdr_underlay: true
          ngdr_underlay_neighbor: 10.254.253.2
        - id: 966
          type: vlan
          description: Transfer to rt-hec14-vpn-01a
          mtu: 9100
          ip: 10.254.253.11/31
          ngdr_underlay: true
          ngdr_underlay_neighbor: 10.254.253.10
        - id: 1
          description: rt-hec14-core-01a, Fo0/2/1
          po: 1101
          speed: 40gfull
        - id: 2
          description: rt-hec14-core-01b, Fo0/2/1
          po: 1102
          speed: 40gfull
        - id: 3
          description: rt-hec14-cwan-01a, Fo1/0/0
          po: 1103
          speed: 40gfull
        - id: 4
          description: rt-hec14-idc-01a, Fo1/0/0
          po: 1104
          speed: 40gfull
        - id: 27
          description: sw-hec14-brdr-01a, Et27
          po: 42
        - id: 28
          description: sw-hec14-brdr-01a, Et28
          po: 42
        - id: 5
          description: rt-hec14-vpn-01a
          po: 1106
          speed: 40gfull
        - id: 6
          description: rt-hec14-inet-01a
          po: 1105
          speed: 40gfull
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 1101
          description: rt-hec14-core-01a
          trunk: all
        - id: 1102
          description: rt-hec14-core-01b
          trunk: all
        - id: 1103
          description: rt-hec14-cwan-01a
          trunk: all
        - id: 1104
          description: rt-hec14-idc-01a
          trunk: all         
        - id: 1105
          description: rt-hec14-inet-01a
          trunk: all  
        - id: 1106
          description: rt-hec14-vpn-01a
          trunk: all        
    - number: 2a
      uplinks:
        - 51
        - 52
        - 53
        - 54
      uplinks_speed: 100gfull
      snmp:
        contact: 34672186:ncons-hec14-oob-01.net 1011
        location: CA-TOR2-CAGE3-CAB41-U41
      lo900_suffix: 43
      mgmt1_suffix: 23
      spine_port_towards_leaf: Et3/5/1
      ports:
        - id: 49
          description: sw-hec14-brdr-02b, Et49
          po: 42
        - id: 50
          description: sw-hec14-brdr-02b, Et50
          po: 42
        - id: 48
          description: ->naa-hec14-01, in-band
          po: 48
          access_vlan: 916
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 48
          description: ->naa-hec14-01, in-band
          access_vlan: 916
    - number: 2b
      uplinks:
        - 51
        - 52
        - 53
        - 54
      uplinks_speed: 100gfull
      snmp:
        contact: 34672187:ncons-hec14-oob-01.net 1012
        location: CA-TOR2-CAGE3-CAB41-U39
      lo900_suffix: 44
      mgmt1_suffix: 24
      spine_port_towards_leaf: Et3/6/1
      ports:
        - id: 49
          description: sw-hec14-brdr-02a, Et49
          po: 42
        - id: 50
          description: sw-hec14-brdr-02a, Et50
          po: 42
        - id: 48
          description: ->naa-hec14-01, in-band
          po: 48
          access_vlan: 916
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 48
          description: ->naa-hec14-01, in-band
          access_vlan: 916
    - number: 3a
      uplinks:
        - 29
        - 30
        - 31
        - 32
      uplinks_speed: 100gfull
      snmp:
        contact: 34672184:ncons-hec14-oob-01.net 1015
        location: CA-TOR2-CAGE3-CAB42-U41
      lo900_suffix: 45
      mgmt1_suffix: 25
      spine_port_towards_leaf: Et3/7/1
      ports:
        - id: 1
          description: rt-hec14-core-01c, Fo0/2/0
          po: 1101
        - id: 2
          description: rt-hec14-core-01d, Fo0/2/0
          po: 1102
        - id: 3
          description: rt-hec14-cwan-01b, Fo0/0/0
          po: 1103
        - id: 4
          description: rt-hec14-idc-01b, Fo0/0/0
          po: 1104            
        - id: 5
          description: rt-hec14-vpn-01b
          po: 1106
        - id: 6
          description: rt-hec14-inet-01b
          po: 1105  
        - id: 27
          description: sw-hec14-brdr-03b, Et27
          po: 42
        - id: 28
          description: sw-hec14-brdr-03b, Et28
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 1101
          description: rt-hec14-core-01c
          trunk: all
        - id: 1102
          description: rt-hec14-core-01d
          trunk: all
        - id: 1103
          description: rt-hec14-cwan-01b
          trunk: all
        - id: 1104
          description: rt-hec14-idc-01b
          trunk: all         
        - id: 1105
          description: rt-hec14-inet-01b
          trunk: all 
        - id: 1106
          description: rt-hec14-vpn-01b
          trunk: all    
    - number: 3b
      uplinks:
        - 25
        - 26
        - 35
        - 36
      uplinks_speed: 100gfull
      snmp:
        contact: 34672185:ncons-hec14-oob-01.net 1016
        location: CA-TOR2-CAGE3-CAB42-U39
      lo900_suffix: 46
      mgmt1_suffix: 26
      spine_port_towards_leaf: Et3/8/1
      ports:
        - id: 1
          description: rt-hec14-core-01c, Fo0/2/1
          po: 1101
        - id: 2
          description: rt-hec14-core-01d, Fo0/2/1
          po: 1102
        - id: 3
          description: rt-hec14-cwan-01b, Fo1/0/0
          po: 1103
        - id: 4
          description: rt-hec14-idc-01b, Fo1/0/0
          po: 1104  
        - id: 5
          description: rt-hec14-vpn-01b
          po: 1106
        - id: 6
          description: rt-hec14-inet-01b
          po: 1105  
        - id: 27
          description: sw-hec14-brdr-03a, Et27
          po: 42
        - id: 28
          description: sw-hec14-brdr-03a, Et28
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 1101
          description: rt-hec14-core-01c
          trunk: all
        - id: 1102
          description: rt-hec14-core-01d
          trunk: all
        - id: 1103
          description: rt-hec14-cwan-01b
          trunk: all
        - id: 1104
          description: rt-hec14-idc-01b
          trunk: all         
        - id: 1105
          description: rt-hec14-inet-01b
          trunk: all 
        - id: 1106
          description: rt-hec14-vpn-01b
          trunk: all   
  str:
    - number: 1a
      spine_port_towards_leaf: Et3/9/1
      uplinks:
        - 25
        - 26
        - 35
        - 36
      ports:
        - id: 30/1
          description: sw-hec14-str-01b, Et30
          po: 42
        - id: 31/1
          description: sw-hec14-str-01b, Et31
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
    - number: 1b
      spine_port_towards_leaf: Et3/10/1
      uplinks:
        - 25
        - 26
        - 35
        - 36
      ports:
        - id: 30/1
          description: sw-hec14-str-01a, Et30
          po: 42
        - id: 31/1
          description: sw-hec14-str-01a, Et31
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
    - number: 2a
      spine_port_towards_leaf: Et3/11/1
      uplinks_speed: 100gfull
      uplinks:
        - 51/1
        - 52/1
        - 53/1
        - 54/1
      ports:
        - id: 49/1
          description: sw-hec14-str-02b, Et49
          speed: 100gfull
          po: 42
        - id: 50/1
          description: sw-hec14-str-02b, Et50
          speed: 100gfull
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
    - number: 2b
      spine_port_towards_leaf: Et3/12/1
      uplinks_speed: 100gfull
      uplinks:
        - 51/1
        - 52/1
        - 53/1
        - 54/1
      ports:
        - id: 49/1
          description: sw-hec14-str-02b, Et49
          speed: 100gfull
          po: 42
        - id: 50/1
          description: sw-hec14-str-02b, Et50
          speed: 100gfull
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
  shs:
    - number: 1a
      uplinks:
        - 25
        - 26
        - 35
        - 36
      spine_port_towards_leaf: Et4/3/1
      ports:
        - id: 32
          description: CIS-iSCSI
          type: vlan
          ip: 
        - id: 1/1
          description: ->hec14f00501,e4a via MPO
          po: 10
        - id: 25/1
          description: sw-hec14-shs-01b, Et25
          po: 42
        - id: 26/1
          description: sw-hec14-shs-01b, Et26
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 10
          description: hec14f00501
          trunk: 30,32,40,50,55,130,2001-2499
    - number: 1b
      uplinks:
        - 25
        - 26
        - 35
        - 36
      spine_port_towards_leaf: Et4/4/1
      ports:
        - id: 32
          description: CIS-iSCSI
          type: vlan
          ip: 
        - id: 1/1
          description: ->hec14f00501,e4a via MPO
          po: 10
        - id: 25/1
          description: sw-hec14-shs-01a, Et25
          po: 42
        - id: 26/1
          description: sw-hec14-shs-01a, Et26
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 10
          description: hec14f00501
          trunk: 30,32,40,50,55,130,2001-2499
  hvv_hvx_acl_rules: |
      10 permit vlan 50 0x000 icmp any any
      20 permit vlan 50 0x000 pim any any
      30 permit vlan 50 0x000 92 any any
      40 permit vlan 50 0x000 vrrp any any
      50 permit vlan 50 0x000 ip any 224.0.0.0/5
      60 permit vlan 50 0x000 ip 198.18.80.0/22 host 198.18.83.255
      70 permit vlan 50 0x000 ip 198.18.80.0/22 198.18.83.0/24
      80 permit vlan 50 0x000 ip 198.18.83.0/24 198.18.80.0/22
      90 permit vlan 50 0x000 ip 198.18.80.0/22 host 198.18.80.1
      99 deny vlan 50 0x000 ip 198.18.80.0/22 198.18.80.0/22
      110 permit vlan 50 0x000 ip 198.18.80.0/22 any
      119 permit vlan 50 0x000 ip any any
      130 permit vlan 55 0x000 icmp any any
      140 permit vlan 55 0x000 pim any any
      150 permit vlan 55 0x000 92 any any
      160 permit vlan 55 0x000 vrrp any any
      170 permit vlan 55 0x000 ip any 224.0.0.0/5
      180 permit vlan 55 0x000 ip 100.125.0.0/16 host 100.125.255.255
      190 permit vlan 55 0x000 ip 100.125.0.0/16 100.125.240.0/20
      200 permit vlan 55 0x000 ip 100.125.240.0/20 100.125.0.0/16
      210 permit vlan 55 0x000 ip 100.125.0.0/16 host 100.125.0.1
      219 deny vlan 55 0x000 ip 100.125.0.0/16 100.125.0.0/16
      230 permit vlan 55 0x000 ip 100.125.0.0/16 any
      239 permit vlan 55 0x000 ip any any
      250 permit vlan 60 0x000 icmp any any
      260 permit vlan 60 0x000 pim any any
      270 permit vlan 60 0x000 92 any any
      280 permit vlan 60 0x000 vrrp any any
      290 permit vlan 60 0x000 ip any 224.0.0.0/5
      300 permit vlan 60 0x000 ip 198.18.88.0/21 host 198.18.91.255
      310 permit vlan 60 0x000 ip 198.18.88.0/21 host 198.18.88.1
      319 deny vlan 60 0x000 ip 198.18.88.0/21 198.18.88.0/21
      329 permit vlan 60 0x000 ip 198.18.88.0/21 any
      340 permit vlan 60 0x000 ip 198.19.128.0/20 host 198.19.143.255
      350 permit vlan 60 0x000 ip 198.19.128.0/20 host 198.19.128.1
      359 deny vlan 60 0x000 ip 198.19.128.0/20 198.19.128.0/20
      370 permit vlan 60 0x000 ip 198.19.128.0/20 any
      379 permit vlan 60 0x000 ip any any
      389 permit ip any any
  hana_acl_rules: |
      10 permit ip any any
