---
# file: group_vars/hec13
idrac:
  # IDRAC IP reserved in IPAM :
  ip: "10.9.245.254"
  mask: "255.255.254.0"
  gw: "10.9.244.1"
  # IDRAC Hostname reserved in IPAM :
  name: "naa-hec13-01-idrac"
  # dns not required but set to the landscape dns1 and dns2 reserved in TIC HECxx-CIS01-DNS01:
  dns1: "100.127.37.1"
  dns2: "100.127.37.2"
  domain: "net.sap.corp"
  password: "arista"

cva:
  # CVA IP reserved in IPAM :
  ip: "10.9.244.11"
  mask: "255.255.254.0"
  gw: "10.9.244.1"
  # CVA Hostname reserved in IPAM :
  name: "naa-hec13-01"
  # dns not required but set to the landscape dns1 and dns2 reserved in TIC HECxx-CIS01-DNS01:
  dns1: "100.127.37.1"
  dns2: "100.127.37.2"
  domain: "net.sap.corp"
  password: "arista"

oob01:
  dhcp:
    prefix: "10.9.244.0"
    mask: "255.255.254.0"
    router: "10.9.244.1"
    # .248 and .249 reserved in IPAM as for installation or server replacement purpose:
    idrac_ip: "10.9.245.248"
    cva_ip: "10.9.245.249"

cvp:
  version: "cvp-2019.1.2-kvm.tar"
  path_to_cvp_file: "/ens/bin/images/arista/"
  ip_eth0: "10.9.245.253"
  # inband transport ip for cvp (for configuration purpose) reserved in TIC
  ip_eth1: "10.255.185.69"
  mask_eth0: "255.255.254.0"
  mask_eth1: "255.255.255.240"
  gw: "10.9.244.1"
  name: "naa-hec13-cvp-01.net.sap.corp"
  # nsq-dns-01 and dns-02 :
  dns1: "10.4.202.200"
  dns2: "10.4.12.200"
  domain: "net.sap.corp"
  # ntp as used for hec16 - Ashburn
  ntp1: "10.4.12.100"
  ntp2: "10.4.12.102"
  device_int: eth0
  cluster_int: eth1
  ingest_key: "SecureKey13"
  vmname: "cvp-hec13"
  KvmDomain: "cvp"
  password: "arista"
  backupuser: "cvpbkp"
  eth1_routes:
    # HEC1x-NW-MGMT01 (VLAN900)
    - prefix: "198.19.232.0"
      mask: "24"
      # This IP is the Firewall but for the begining we bypass the firewall
      nexthop: "10.255.185.78"
      # HEC1x-NW-MGMT05 (Lo900)
    - prefix: "198.19.180.0"
      mask: "24"
      # This IP is the Firewall but for the begining we bypass the firewall
      nexthop: "10.255.185.78"
  dhcp:
    prefix: "10.9.244.0"
    mask: "255.255.254.0"
    range_low: "10.9.245.224"
    range_high: "10.9.245.247"
  aaa_config:
    aaa_type: "RADIUS"
    servers:
      # Below IP is the same as for Ashburn
      - ip: "10.4.201.55"
        secret: secretRadPw
        authMode: "PAP"
        authPort: 1645
        accPort: 1646
        status: "Enabled"
        # Below IP is the same as for Ashburn
      - ip: "169.145.33.70"
        secret: secretRadPw
        authMode: "PAP"
        authPort: 1645
        accPort: 1646
        status: "Enabled"

hec:
  hec_nr: "13"
  hana_hvx_descriptions_PO_MIN: 101
  hana_hvx_descriptions_PO_MAX: 124
  hvv_descriptions_PO_MAX: 24
  hvv_descriptions_PO_RANGE: "{101,151}"
  ma_domain: "net.sap.corp"
  lo900_domain: "yyz.hec.sap.biz"
  vl900_domain: "yyz.hec.sap.biz"
  vl900_mask: 24
  vl900_def_gw: 198.19.232.1
  vl900_net: 198.19.232.0/25
  lo900_net: 198.19.180.0/24
  lo900_prefix: 198.19.180
  inband_trans_brdr: 10.255.185.78
  inband_trans_brdr_mac: 00:1c:73:00:00:96
  inband_trans_net: 10.255.185.64/28
  inband_trans_prefix: 10.255.185
  inband_trans_mask: 28
  inband_trans_gw_vlan: Vlan916
  inband_trans_gw: 10.255.186.65
  inband_trans_cvx: 10.255.185.68
  inband_trans_cvp: 10.255.185.69
  oob_def_gw: 10.9.244.1
  oob_prefix: 10.9.244
  oob_mask: 23
  oob_vrf: OOB
  oob_cvx: 10.9.247.252
  oob_cvp: 10.9.247.253
  as_low: 4200998673
  as_high: 4200999871
  cvp_ingest_key: SecureKey13
  dns1: 100.127.37.1
  dns2: 100.127.37.2
  ntp1: 100.127.37.37
  ntp2: 100.127.37.38
  snmp1: 147.204.148.100
  snmp2: 147.204.148.87
  syslog1: 100.127.37.69
  syslog2: 147.204.133.69
  syslog3: 147.204.146.42
  radius1: 10.4.201.55
  radius2: 169.145.33.70
  admin_mpls:
    - prefix_mask: "10.9.244.0/23"
      sequence: "20"
  admin_sw_interface: Ethernet1
  admin_sw_description_oob1a: "tordc01-adm-03-co Ethernet1/18"
  admin_sw_description_oob1b: "tordc01-adm-04-co Ethernet1/18"
  admin_sw_prefix: 10.255.194
  admin_sw_mask: 31
  admin_sw_ip_oob1a: 10.255.194.12
  admin_sw_ip_oob1b: 10.255.194.14
  admin_sw_neig_ip_oob1a: 10.255.194.13
  admin_sw_neig_as_oob1a: 1.463
  admin_sw_neig_ip_oob1b: 10.255.194.15
  admin_sw_neig_as_oob1b: 64536
  oob01_lo0_prefix: 198.19.251
  oob01_as: 64531.13
  spine_nr:
    - 11
    - 12
    - 13
    - 14
  spine:
    # valid models are: 7504, 7508, 7280
    model: 7504
    # number of linecards if spine is modular switch
    # if spine model is fixed chassis then linecards needs to have value of '1'
    linecards: 4
  fabric:
    # valid modes are: manual, cvx, evpn, manual
    vtep_distribution_mode: evpn
    interlink_mtu: 9214
    # valid speeds are 40gfull, 100gfull
    interlink_speed: 100gfull
    bgp_maximum_routes: 12000
    evpn_maximum_routes: 0
    mlag_a_ip: 198.19.224.1
    mlag_b_ip: 198.19.224.2
    leaf_models:
      - model: 7160-32CQ
        uplink_ports: 29/1,30/1,31/1,32/1
      - model: 7160-48YC6
        uplink_ports: 51/1,52/1,53/1,54/1
      - model: 7280QR-C36
        uplink_ports: 25/1,26/1,35/1,36/1
      - model: 7280SR-48C6
        uplink_ports: 51/1,52/1,53/1,54/1
  oob01a_snmp_contact: 34672518:ncons-hec13-oob-02:1006
  oob01a_snmp_location: Toronto1-(TR3)-Cage2-3.1-12-39
  oob01b_snmp_contact: 34672517:ncons-hec13-oob-02:1007
  oob01b_snmp_location: Toronto1-(TR3)-Cage2-3.1-12-38
  oobs_2_7:
    - number: 02
      snmp_contact: 34672508:ncons-hec13-oob-01:1023
      snmp_location: Toronto1-(TR3)-Cage2-3.1-11-41
      ip_last_octett: 4
    - number: 03
      snmp_contact: 34672507:ncons-hec13-oob-03:1003
      snmp_location: Toronto1-(TR3)-Cage1-1.1-9-34
      ip_last_octett: 5
    - number: 04
      snmp_contact: unknown
      snmp_location: unknown
      ip_last_octett: 6
    - number: 05
      snmp_contact: unknown
      snmp_location: unknown
      ip_last_octett: 7
    - number: 06
      snmp_contact: unknown
      snmp_location: unknown
      ip_last_octett: 8
  brdr:
    - number: 1a
      uplinks:
        - 29
        - 30
        - 31
        - 32
      spine_port_towards_leaf: Et3/3/1
      ports:
        - id: 1/1
          description: rt-hec13-core-01a, Fo0/2/0
          po: 1101
        - id: 2/1
          description: rt-hec13-core-01b, Fo0/2/0
          po: 1102
        - id: 3/1
          description: rt-hec13-cwan-01a, Fo0/0/0
          po: 1103
        - id: 4/1
          description: rt-hec13-idc-01a,  Fo0/0/0
          po: 1104
        - id: 5/1
          description: rt-hec13-vpn-01a,  Fo0/2/0
          po: 1106
        - id: 6/1
          description: rt-hec13-inet-01a,  Fo0/2/0
          po: 1105
        - id: 27/1
          description: sw-hec13-brdr-01b,  Et27/1
          po: 42
        - id: 28/1
          description: sw-hec13-brdr-01b,  Et28/1
          po: 42
        - id: 961
          description: ->Transfer to rt-hec13-cwan-01a
          type: vlan
          ip: 10.254.253.1/31
        - id: 965
          description: ->Transfer to rt-hec13-vpn-01a
          type: vlan
          ip: 10.254.253.9/31
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 1101
          description: rt-hec13-core-01a
          trunk: all
        - id: 1102
          description: rt-hec13-core-01b
          trunk: all
        - id: 1103
          description: rt-hec13-cwan-01a
          trunk: all
        - id: 1104
          description: rt-hec13-idc-01a
          trunk: all
        - id: 1105
          description: rt-hec13-inet-01a
          trunk: all
        - id: 1106
          description: rt-hec13-vpn-01a
          trunk: all
    - number: 1b
      uplinks:
        - 29
        - 30
        - 31
        - 32
      spine_port_towards_leaf: Et3/4/1
      ports:
        - id: 1/1
          description: rt-hec13-core-01a, Fo0/2/1
          po: 1101
        - id: 2/1
          description: rt-hec13-core-01b, Fo0/2/1
          po: 1102
        - id: 3/1
          description: rt-hec13-cwan-01a, Fo1/0/0
          po: 1103
        - id: 4/1
          description: rt-hec13-idc-01a,  Fo1/0/0
          po: 1104
        - id: 5/1
          description: rt-hec13-vpn-01a,  Fo0/2/1
          po: 1106
        - id: 6/1
          description: rt-hec13-inet-01a,  Fo0/2/1
          po: 1105
        - id: 27/1
          description: sw-hec13-brdr-01a,  Et27/1
          po: 42
        - id: 28/1
          description: sw-hec13-brdr-01a,  Et28/1
          po: 42
        - id: 962
          description: ->Transfer to rt-hec13-cwan-01a
          type: vlan
          ip: 10.254.253.3/31
        - id: 966
          description: ->Transfer to rt-hec13-vpn-01a
          type: vlan
          ip: 10.254.253.11/31
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 1101
          description: rt-hec13-core-01a
          trunk: all
        - id: 1102
          description: rt-hec13-core-01b
          trunk: all
        - id: 1103
          description: rt-hec13-cwan-01a
          trunk: all
        - id: 1104
          description: rt-hec13-idc-01a
          trunk: all
        - id: 1105
          description: rt-hec13-inet-01a
          trunk: all
        - id: 1106
          description: rt-hec13-vpn-01a
          trunk: all
    - number: 2a
      uplinks:
        - 51
        - 52
        - 53
        - 54
      spine_port_towards_leaf: Et3/5/1
      ports:
        - id: 49/1
          description: sw-hec13-brdr-02b,  Et49/1
          po: 42
        - id: 50/1
          description: sw-hec13-brdr-02b,  Et50/1
          po: 42
        - id: 48
          description: naa-hec13-01, Port11
          po: 48
          access_vlan: 916
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 48
          description: ->naa-hec13-01, in-band
          access_vlan: 916
    - number: 2b
      uplinks:
        - 51
        - 52
        - 53
        - 54
      spine_port_towards_leaf: Et3/6/1
      ports:
        - id: 49/1
          description: sw-hec13-brdr-02a,  Et49/1
          po: 42
        - id: 50/1
          description: sw-hec13-brdr-02a,  Et50/1
          po: 42
        - id: 48
          description: naa-hec13-01, Port12
          po: 48
          access_vlan: 916
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 48
          description: ->naa-hec13-01, in-band
          access_vlan: 916
    - number: 3a
      uplinks:
        - 29
        - 30
        - 31
        - 32
      spine_port_towards_leaf: Et3/7/1
      ports:
        - id: 1/1
          description: rt-hec13-core-01c, Fo0/2/0
          po: 1101
        - id: 2/1
          description: rt-hec13-core-01d, Fo0/2/0
          po: 1102
        - id: 3/1
          description: rt-hec13-cwan-01b, Fo0/0/0
          po: 1103
        - id: 4/1
          description: rt-hec13-idc-01b,  Fo0/0/0
          po: 1104
        - id: 5/1
          description: rt-hec13-vpn-01b,  Fo0/2/0
          po: 1106
        - id: 6/1
          description: rt-hec13-inet-01b,  Fo0/2/0
          po: 1105
        - id: 27/1
          description: sw-hec13-brdr-03b,  Et27/1
          po: 42
        - id: 28/1
          description: sw-hec13-brdr-03b,  Et28/1
          po: 42
        - id: 963
          description: ->Transfer to rt-hec13-cwan-01b
          type: vlan
          ip: 10.254.253.5/31
        - id: 967
          description: ->Transfer to rt-hec13-vpn-01b
          type: vlan
          ip: 10.254.253.13/31
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 1101
          description: rt-hec13-core-01c
          trunk: all
        - id: 1102
          description: rt-hec13-core-01d
          trunk: all
        - id: 1103
          description: rt-hec13-cwan-01b
          trunk: all
        - id: 1104
          description: rt-hec13-idc-01b
          trunk: all
        - id: 1105
          description: rt-hec13-inet-01a
          trunk: all
        - id: 1106
          description: rt-hec13-vpn-01a
          trunk: all
    - number: 3b
      uplinks:
        - 29
        - 30
        - 31
        - 32
      spine_port_towards_leaf: Et3/8/1
      ports:
        - id: 1/1
          description: rt-hec13-core-01c, Fo0/2/1
          po: 1101
        - id: 2/1
          description: rt-hec13-core-01d, Fo0/2/1
          po: 1102
        - id: 3/1
          description: rt-hec13-cwan-01b, Fo1/0/0
          po: 1103
        - id: 4/1
          description: rt-hec13-idc-01b,  Fo1/0/0
          po: 1104
        - id: 5/1
          description: rt-hec13-vpn-01b,  Fo0/2/1
          po: 1106
        - id: 6/1
          description: rt-hec13-inet-01b,  Fo0/2/1
          po: 1105
        - id: 27/1
          description: sw-hec13-brdr-03a,  Et27/1
          po: 42
        - id: 28/1
          description: sw-hec13-brdr-03a,  Et28/1
          po: 42
        - id: 964
          description: ->Transfer to rt-hec13-cwan-01b
          type: vlan
          ip: 10.254.253.7/31
        - id: 968
          description: ->Transfer to rt-hec13-vpn-01b
          type: vlan
          ip: 10.254.253.15/31
      port_channels:
        - id: 42
          description: mlag peer link
        - id: 1101
          description: rt-hec13-core-01c
          trunk: all
        - id: 1102
          description: rt-hec13-core-01d
          trunk: all
        - id: 1103
          description: rt-hec13-cwan-01b
          trunk: all
        - id: 1104
          description: rt-hec13-idc-01b
          trunk: all
        - id: 1105
          description: rt-hec13-inet-01a
          trunk: all
        - id: 1106
          description: rt-hec13-vpn-01a
          trunk: all
  str:
    - number: 1a
      spine_port_towards_leaf: Et3/9/1
      uplinks:
        - 25
        - 26
        - 35
        - 36
      ports:
        - id: 30/1
          description: sw-hec13-str-01b, Et30/1
          po: 42
        - id: 31/1
          description: sw-hec13-str-01b, Et31/1
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
    - number: 1b
      spine_port_towards_leaf: Et3/10/1
      uplinks:
        - 25
        - 26
        - 35
        - 36
      ports:
        - id: 30/1
          description: sw-hec13-str-01a, Et30/1
          po: 42
        - id: 31/1
          description: sw-hec13-str-01a, Et31/1
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
    - number: 2a
      spine_port_towards_leaf: Et3/11/1
      uplinks:
        - 51
        - 52
        - 53
        - 54
      ports:
        - id: 49/1
          description: sw-hec13-str-02b, Et49/1
          po: 42
        - id: 50/1
          description: sw-hec13-str-02b, Et50/1
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
    - number: 2b
      spine_port_towards_leaf: Et3/12/1
      uplinks:
        - 51
        - 52
        - 53
        - 54
      ports:
        - id: 49/1
          description: sw-hec13-str-02a, Et49/1
          po: 42
        - id: 50/1
          description: sw-hec13-str-02a, Et50/1
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
  shs:
    - number: 1a
      uplinks:
        - 25
        - 26
        - 35
        - 36
      spine_port_towards_leaf: Et4/3/1
      ports:
        - id: 25/1
          description: sw-hec13-shs-01b, Et25
          po: 42
        - id: 26/1
          description: sw-hec13-shs-01b, Et26
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
    - number: 1b
      uplinks:
        - 25
        - 26
        - 35
        - 36
      spine_port_towards_leaf: Et4/4/1
      ports:
        - id: 25/1
          description: sw-hec13-shs-01a, Et25
          po: 42
        - id: 26/1
          description: sw-hec13-shs-01a, Et26
          po: 42
      port_channels:
        - id: 42
          description: mlag peer link
  hvv_hvx_acl_rules: |
      10 permit vlan 50 0x000 icmp any any
      20 permit vlan 50 0x000 pim any any
      30 permit vlan 50 0x000 92 any any
      40 permit vlan 50 0x000 vrrp any any
      50 permit vlan 50 0x000 ip any 224.0.0.0/5
      60 permit vlan 50 0x000 ip 100.96.16.0/22 host 100.96.19.255
      70 permit vlan 50 0x000 ip 100.96.16.0/22 100.96.19.0/24
      80 permit vlan 50 0x000 ip 100.96.19.0/24 100.96.16.0/22
      90 permit vlan 50 0x000 ip 100.96.16.0/22 host 100.96.16.1
      100 deny vlan 50 0x000 ip 100.96.16.0/22 100.96.16.0/22 log
      110 permit vlan 50 0x000 ip 100.96.16.0/22 any
      120 permit vlan 50 0x000 ip any any log
      130 permit vlan 60 0x000 icmp any any
      140 permit vlan 60 0x000 pim any any
      150 permit vlan 60 0x000 92 any any
      160 permit vlan 60 0x000 vrrp any any
      170 permit vlan 60 0x000 ip any 224.0.0.0/5
      180 permit vlan 60 0x000 ip 100.96.24.0/21 host 100.96.27.255
      190 permit vlan 60 0x000 ip 100.96.24.0/21 host 100.96.31.255
      200 permit vlan 60 0x000 ip 100.96.24.0/21 host 100.96.24.1
      210 deny vlan 60 0x000 ip 100.96.24.0/21 100.96.24.0/21 log
      220 permit vlan 60 0x000 ip 100.96.24.0/21 any
      230 permit vlan 60 0x000 ip any any log
      240 permit ip any any
  hana_acl_rules: |
      10 permit icmp any any
      20 permit pim any any
      30 permit 92 any any
      40 permit vrrp any any
      50 permit ip any 224.0.0.0/5
      60 permit ip 100.96.8.0/23 host 100.96.9.255
      70 permit ip 100.96.8.0/23 host 100.96.8.4
      80 permit ip host 100.96.8.4 100.96.8.0/23
      90 permit ip 100.96.8.0/23 host 100.96.8.5
      100 permit ip host 100.96.8.5 100.96.8.0/23
      110 permit ip 100.96.8.0/23 host 100.96.8.6
      120 permit ip 100.96.8.0/23 host 100.96.8.5
      130 permit ip host 100.96.8.6 100.96.8.0/23
      140 permit ip 100.96.8.0/23 100.96.9.224/27
      150 permit ip 100.96.9.224/27 100.96.8.0/23
      160 permit ip 100.96.8.0/23 host 100.96.8.1
      170 deny ip 100.96.8.0/23 100.96.8.0/23
      180 permit ip 100.96.8.0/23 any
      190 permit ip any any

