---
- name: Playbook to demonstrate cv_container module.
  hosts: hec01
  connection: local
  gather_facts: no
  collections:
    - arista.cvp
  vars:
    container:
      HEC:
        parent_container: Fabric
      HEC-IPMI:
        parent_container: HEC
      HEC-Out of band:
        parent_container: HEC
      HEC-External Connectivity:
        parent_container: HEC
      HEC-CWAN:
        parent_container: HEC
      HEC-FWT:
        parent_container: HEC
      HEC-InterDC:
        parent_container: HEC
      HEC-Backup Routers:
        parent_container: HEC
      HEC-Switched Fabric:
        parent_container: HEC
      HEC-Routed Fabric:
        parent_container: HEC
      HEC-Core:
        parent_container: HEC-Switched Fabric
      HEC-Top of rack:
        parent_container: HEC-Switched Fabric
      HEC-Spine:
        parent_container: HEC-Routed Fabric
      HEC-NGDR:
        parent_container: HEC-Routed Fabric
      HEC-Leaf:
        parent_container: HEC-Routed Fabric
      HEC-Service leaf:
        parent_container: HEC-Leaf
      HEC-Border leaf:
        parent_container: HEC-Leaf
      HEC-Storage leaf:
        parent_container: HEC-Leaf
      HEC-Special leaf:
        parent_container: HEC-Leaf
      HEC-HANA leaf:
        parent_container: HEC-Leaf
      HEC-HV leaf:
        parent_container: HEC-Leaf
      HEC-VMWare leaf:
        parent_container: HEC-HV leaf
      HEC-Xen leaf:
        parent_container: HEC-HV leaf

  tasks:
    - name: "Gather CVP facts from {{inventory_hostname}}"
      cv_facts:
      register: cvp_facts
      tags:
        - always

    - name: "Build Container topology on {{inventory_hostname}}"
      arista.cvp.cv_container:
        topology: "{{container}}"
        cvp_facts: "{{cvp_facts.ansible_facts}}"
        mode: merge
