---
- name: Retrieve the cell switch configrations from configlet builders
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - arista.cvp

  tasks:
    - name: "Gather CVP facts from {{inventory_hostname}}"
      cv_facts:
        facts:
          configlets
      register: cvp_facts

    #- name: print gathered facts
    #  debug:
    #    msg: '{{ cvp_facts }}'

    - name: "Save each configlet to local file in roles/cvp/files/builder_generated_configs/{{inventory_hostname}}/"
      copy: content='{{item.config}}' dest="roles/cvp/files/builder_generated_configs/{{inventory_hostname}}/{{item.name}}"
      loop: '{{ cvp_facts.ansible_facts.configlets }}'
      when: item.name is search('sw-hec..-(hana|hvv|hvx).*')
