---
- name: Playbook to demonstrate cv_container module.
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - arista.cvp

  tasks:
    - name: "Gather CVP facts from {{inventory_hostname}}"
      cv_facts:
        facts:
          configlets
      register: cvp_facts

    - name: print gathered facts
      debug:
        msg: '{{ cvp_facts }}'

    - name: try to print only names
      debug:
        msg: "{{ item['name'] }}\n{{ item['config'] }}\n"
      loop: '{{ cvp_facts.ansible_facts.configlets }}'
      when: item.name is search('sw-mlag-b')
