---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Check if roles/cvp/files/builder_generated_configs exists
    stat:
      path: 'roles/cvp/files/builder_generated_configs'
    register: dir_to_delete

  - name: Delete roles/cvp/files/builder_generated_configs if exists
    file:
      state: absent
      path: 'roles/cvp/files/builder_generated_configs'
    when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir
