---
- hosts: all
  gather_facts: no
  tasks:
  - name: Check if {{role_path}}/files/builder_generated_configs exists
    delegate_to: 127.0.0.1
    stat:
      path: '{{role_path}}/files/builder_generated_configs'
    register: dir_to_delete

  - name: Delete {{role_path}}/files/builder_generated_configs if exists
    delegate_to: 127.0.0.1
    file:
      state: absent
      path: '{{role_path}}/files/builder_generated_configs'
    when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir
