---
yml_brdr:
  - number: 1a
    snmp:
      location: incorrect
      contact: incorrect
    oob_ip: 10.177.248.15
    nwmgmt_ip: 198.19.188.15
    uplinks:
      - 29/1
      - 30/1
      - 31/1
      - 32/1
    spine_port_towards_leaf: Et5/1
    ports: []
    port_channels: []
  - number: 1b
    snmp:
      location: incorrect
      contact: incorrect
    oob_ip: 10.177.248.15
    nwmgmt_ip: 198.19.188.15
    uplinks:
      - 29/1
      - 30/1
      - 31/1
      - 32/1
    spine_port_towards_leaf: Et6/1
    ports: []
    port_channels: []
  - number: 3a
    snmp:
      location: incorrect
      contact: incorrect
    oob_ip: 10.177.248.15
    nwmgmt_ip: 198.19.188.15
    uplinks:
      - 29/1
      - 30/1
      - 31/1
      - 32/1
    spine_port_towards_leaf: Et7/1
    ports: []
    port_channels: []
  - number: 3b
    snmp:
      location: incorrect
      contact: incorrect
    oob_ip: 10.177.248.15
    nwmgmt_ip: 198.19.188.15
    uplinks:
      - 29/1
      - 30/1
      - 31/1
      - 32/1
    spine_port_towards_leaf: Et8/1
    ports: []
    port_channels: []
  - number: 4a # updated from 1a to 4a - 4 is the special leaf 7280QR-C36 towards legacy
    is_l2l3_transit: true
    snmp:
      location: RU-MOW1-CAGE3-13/05/09/33 # correct
      contact: 34847172:ncons-hec11-07.hec.oob.net.sap:1004 # correct
    oob_ip: 10.177.248.17  # correct see nslookup
    nwmgmt_ip: 198.19.188.17 # correct see nslookup
    uplinks:
      - 25/1 # 7280QR-C36
      - 26/1 # 7280QR-C36
      - 35/1 # 7280QR-C36
      - 36/1 # 7280QR-C36
    spine_port_towards_leaf: Et1/1 # changed from Et3/3/1 to 1/1 as per the MCS  and is correct
    ports:
      - id: 900
        type: vlan
        description: NW-MGMT
        ip: 198.19.230.83/25
        vrrp: # VRRP gw for FWTRANS towards HEC01 Fabric
          - id: 250
            priority: 105
            ip: 198.19.230.85
            auth: FWTTRANS
      - id: 1/1 # 40G Link to L2 core switch
        description: sw-hec11-101 Et5/35/4
        po: 1101
      - id: 1/2 # 40G Link to L2 core switch
        description: sw-hec11-102 Et5/35/4
        po: 1102
      - id: 30/1
        description: sw-hec11-brdr-04a Et30/1
        po: 42
      - id: 31/1
        description: sw-hec11-brdr-04a Et31/1
        po: 42
    port_channels:
      - id: 42
        description: mlag peer link
      - id: 1101
        description: sw-hec11-101
        trunk: all
      - id: 1102
        description: sw-hec11-102
        trunk: all
  - number: 4b
    is_l2l3_transit: true
    snmp:
      location: RU-MOW1-CAGE3-13/05/12/33 # correct
      contact: 34847173:ncons-hec11-08.hec.oob.net.sap:1004 # correct
    oob_ip: 10.177.248.18  # correct see nslookup
    nwmgmt_ip: 198.19.188.18 # correct see nslookup
    uplinks:
      - 25/1 # 7280QR-C36
      - 26/1 # 7280QR-C36
      - 35/1 # 7280QR-C36
      - 36/1 # 7280QR-C36
    spine_port_towards_leaf: Et2/1 # checked and as per mcs
    ports:
      - id: 900
        type: vlan
        description: NW-MGMT
        ip: 198.19.230.84/24
        vrrp: # VRRP gw for FWTRANS towards HEC01 Fabric
          - id: 250
            priority: 100
            ip: 198.19.230.85
            auth: FWTTRANS
      - id: 1/1 # 40G Link to L2 core switch
        description: sw-hec11-101 Et5/36/4
        po: 1101
      - id: 1/2 # 40G Link to L2 core switch
        description: sw-hec11-102 Et5/36/4
        po: 1102
      - id: 30/1
        description: sw-hec11-brdr-04a Et30/1
        po: 42
      - id: 31/1
        description: sw-hec11-brdr-04a Et31/1
        po: 42
    port_channels:
      - id: 42
        description: mlag peer link
      - id: 1101
        description: sw-hec11-101
        trunk: all
      - id: 1102
        description: sw-hec11-102
        trunk: all
  - number: 2a
    snmp:
      location: RU-MOW1-CAGE3-13/05/08/33 # correct
      contact: 34847184:ncons-hec11-07.hec.oob.net.sap:1003 # correct
    oob_ip: 10.177.248.15 # corect see nslookup
    nwmgmt_ip: 198.19.188.15 # correct see nslookup
    uplinks:
      - 51/1 # 7280SR-48C6
      - 52/1
      - 53/1
      - 54/1
    spine_port_towards_leaf: Et3/1
    ports:
      - id: 1
        description: lb-hec11-01, eth1.1
        speed: 10000full
        trunk: 940
      - id: 2
        description: lb-hec11-01, eth1.2
        speed: 10000full
        trunk: 85,90,95,100,2000-2499
      - id: 3
        description: lb-hec11-01, eth1.3
        trunk: 900
        speed: 10000full
      - id: 4
        description: lb-hec11-01, eth1.4
        trunk: 902
        speed: 10000full
      - id: 48
        description: naa-hec01-01, e3 (inband)
        po: 48
        access_vlan: 916
        speed: 1000full
      - id: 49/1
        description: sw-hec01-brdr-02b, Et51/1
        po: 42
      - id: 50/1
        description: sw-hec01-brdr-02b, Et52/1
        po: 42
      - id: 916
        description: FW-TRANS
        type: vlan
        ip: 10.255.183.76/28 # 183 for hec11
    port_channels:
      - id: 48
        description: naa-hec01-01, in-band
        access_vlan: 916
  - number: 2b
    snmp:
      location: RU-MOW1-CAGE3-13/05/11/33 # correct
      contact: 34847185:ncons-hec11-08.hec.oob.net.sap:1003 # correct
    oob_ip: 10.177.248.16 # corect see nslookup
    nwmgmt_ip: 198.19.188.16 # correct see nslookup
    uplinks:
      - 51/1 # 7280SR-48C6
      - 52/1
      - 53/1
      - 54/1
    spine_port_towards_leaf: Et4/1 # correct
    ports:
      - id: 1
        description: lb-hec11-02, eth1.1
        speed: 10000full
        trunk: 940
      - id: 2
        description: lb-hec11-02, eth1.2
        speed: 10000full
        trunk: 85,90,95,100,2000-2499
      - id: 3
        description: lb-hec11-02, eth1.3
        trunk: 900
        speed: 10000full
      - id: 4
        description: lb-hec11-02, eth1.4
        trunk: 902
        speed: 10000full
      - id: 48
        description: naa-hec01-01, e4 (inband)
        po: 48
        access_vlan: 916
        speed: 1000full
      - id: 49/1
        description: sw-hec01-brdr-02a, Et51/1
        po: 42
      - id: 50/1
        description: sw-hec01-brdr-02a, Et52/1
        po: 42
      - id: 916
        description: FW-TRANS
        type: vlan
        ip: 10.255.183.76/28 # 183 for hec11
    port_channels:
      - id: 48
        description: naa-hec01-01, in-band
        access_vlan: 916
