---
# file: roles/cva/tasks/main.yml

- name: Render and create hostname
  template:
    src: "templates/hostname.j2"
    dest: "/etc/hostname"
  tags:
    - cva

- name: Set hostname with hostnamectl
  command: hostnamectl set-hostname {{ cva.name }}.{{ cva.domain }}
  tags:
    - cva

- name: Render and create ifcfg-devicebr
  template:
    src: "templates/ifcfg-devicebr.j2"
    dest: "/etc/sysconfig/network-scripts/ifcfg-devicebr"
  tags:
    - cva

- name: Render and create resolv.conf
  template:
    src: "templates/resolv.conf.j2"
    dest: "/etc/resolv.conf"
  tags:
    - cva

- name: Restart network service
  command: "systemctl restart network"
  ignore_errors: yes
  tags:
    - cva

- name: Copy netsnmp tar file to CVA
  delegate_to: "{{ cva.ip }}"
  copy:
    src: "{{role_path}}/files/centos-7.6.1810-netsnmp_cva.tar.gz"
    dest: /tmp/centos-7.6.1810-netsnmp_cva.tar.gz
    owner: root
    group: root
    mode: 0755
  tags:
    - cva
    - snmp_cva

- name: Delete installation directory for netsnmp if already exists
  delegate_to: "{{ cva.ip }}"
  file:
    path: "/tmp/netsnmp"
    state: absent
  tags:
    - cva
    - snmp_cva

- name: Create directory for netsnmp installation files (/tmp/netsnmp/)
  delegate_to: "{{ cva.ip }}"
  command: "mkdir /tmp/netsnmp"
  args:
    warn: no
  tags:
    - cva
    - snmp_cva

- name: Extract netsnmp tar file on CVA
  delegate_to: "{{ cva.ip }}"
  command: "tar -zxvf /tmp/centos-7.6.1810-netsnmp_cva.tar.gz -C /tmp/netsnmp"
  tags:
    - cva
    - snmp_cva

- name: Install netsnmp RPMs on the CVA
  delegate_to: "{{ cva.ip }}"
  command: "rpm -ivh --force /tmp/netsnmp/*.rpm"
  args:
    warn: false
  register: rpm_install
  failed_when: rpm_install.rc != 0 and "is already installed" not in rpm_install.stderr
  changed_when: rpm_install.rc == 0
  tags:
    - cva
    - snmp_cva

- name: Render SNMP config and put the file to the CVA machine
  delegate_to: "{{ cva.ip }}"
  template:
    src: "templates/snmpd_cva.conf.j2"
    dest: "/etc/snmp/snmpd.conf"
  tags:
    - cva
    - snmp_cva

- name: Set the snmpd to enabled for persistence after reboot
  delegate_to: "{{ cva.ip }}"
  command: "systemctl enable snmpd"
  tags:
    - cva
    - snmp_cva

- name: Restart snmpd service
  delegate_to: "{{ cva.ip }}"
  service:
    name: snmpd
    state: restarted
  tags:
    - cva
    - snmp_cva

# include operation, installation and initialization tasks
- name: Include cvp_install
  include_tasks: cvp_install.yml
  tags:
    - cvp_install

- name: Include cvp_init
  include_tasks: cvp_init.yml
  tags:
    - cvp_init
    - snmp_cvp
    - pw_reset

- name: Include cvp_ops
  include_tasks: cvp_ops.yml
  tags:
    - cvp_stop
