# file: production

### uncomment or insert the CVA DHCP and CVA Static IP address for the environment you want to work in ###

[CVA-DHCP]
#HEC19
#10.178.147.249
#HEC10
#10.178.143.249

[CVA-STATIC]
#HEC19
#10.178.146.43
#HEC10
#10.178.142.43
