---
configlet_list_dc_specific:
  sw-hec-oob-04: "{{ lookup('file', 'configs/sw-hec-oob-04', errors='warn') }}"
  sw-hec-oob-05: "{{ lookup('file', 'configs/sw-hec-oob-05', errors='warn') }}"
  sw-hec-oob-06: "{{ lookup('file', 'configs/sw-hec-oob-06', errors='warn') }}"
  sw-hec-spine-21: "{{ lookup('file', 'configs/sw-hec-spine-21', errors='warn') }}"
  sw-hec-spine-22: "{{ lookup('file', 'configs/sw-hec-spine-22', errors='warn') }}"
  sw-hec-spine-23: "{{ lookup('file', 'configs/sw-hec-spine-23', errors='warn') }}"
  sw-hec-spine-24: "{{ lookup('file', 'configs/sw-hec-spine-24', errors='warn') }}"
  sw-hec-spine-31: "{{ lookup('file', 'configs/sw-hec-spine-31', errors='warn') }}"
  sw-hec-spine-32: "{{ lookup('file', 'configs/sw-hec-spine-32', errors='warn') }}"
  sw-hec-spine-33: "{{ lookup('file', 'configs/sw-hec-spine-33', errors='warn') }}"
  sw-hec-spine-34: "{{ lookup('file', 'configs/sw-hec-spine-34', errors='warn') }}"
  sw-hec-superspine-1: "{{ lookup('file', 'configs/sw-hec-superspine-1', errors='warn') }}"
  sw-hec-superspine-2: "{{ lookup('file', 'configs/sw-hec-superspine-2', errors='warn') }}"
  sw-hec-superspine-3: "{{ lookup('file', 'configs/sw-hec-superspine-3', errors='warn') }}"
  sw-hec-superspine-4: "{{ lookup('file', 'configs/sw-hec-superspine-4', errors='warn') }}"
  sw-hec-str-03a: "{{ lookup('file', 'configs/sw-hec-str-03a', errors='warn') }}"
  sw-hec-str-03b: "{{ lookup('file', 'configs/sw-hec-str-03b', errors='warn') }}"
  sw-hec-str-04a: "{{ lookup('file', 'configs/sw-hec-str-04a', errors='warn') }}"
  sw-hec-str-04b: "{{ lookup('file', 'configs/sw-hec-str-04b', errors='warn') }}"
  sw-hec-str-05a: "{{ lookup('file', 'configs/sw-hec-str-05a', errors='warn') }}"
  sw-hec-str-05b: "{{ lookup('file', 'configs/sw-hec-str-05b', errors='warn') }}"
  sw-hec-str-06a: "{{ lookup('file', 'configs/sw-hec-str-06a', errors='warn') }}"
  sw-hec-str-06b: "{{ lookup('file', 'configs/sw-hec-str-06b', errors='warn') }}"
  sw-hec-brdr-04a: "{{ lookup('file', 'configs/sw-hec-brdr-04a', errors='warn') }}"
  sw-hec-brdr-04b: "{{ lookup('file', 'configs/sw-hec-brdr-04b', errors='warn') }}"
configlet_filter_list_dc_specific:
  - sw-hec-oob-04
  - sw-hec-oob-05
  - sw-hec-oob-06
  - sw-hec-spine-21
  - sw-hec-spine-22
  - sw-hec-spine-23
  - sw-hec-spine-24
  - sw-hec-spine-31
  - sw-hec-spine-32
  - sw-hec-spine-33
  - sw-hec-spine-34
  - sw-hec-superspine-1
  - sw-hec-superspine-2
  - sw-hec-superspine-3
  - sw-hec-superspine-4
  - sw-hec-str-03a
  - sw-hec-str-03b
  - sw-hec-str-04a
  - sw-hec-str-04b
  - sw-hec-str-05a
  - sw-hec-str-05b
  - sw-hec-str-06a
  - sw-hec-str-06b
  - sw-hec-brdr-04a
  - sw-hec-brdr-04b
