---
- hosts: left_leafs
  gather_facts: no
  tasks:
  - name: Upload MLAG config
    eos_config:
      src: "/home/coder/project/labfiles/AristaLevel5Labs/Ansible-Part2/configs/MLAG-left.cfg"

- hosts: right_leafs
  gather_facts: no
  tasks:
  - name: Upload MLAG config
    eos_config:
      src: "/home/coder/project/labfiles/AristaLevel5Labs/Ansible-Part2/configs/MLAG-right.cfg"
