---
yml_shs:
  - number: 1a
    snmp:
      location: foo
      contact: bar
    oob_ip: 10.178.136.15
    nwmgmt_ip: 198.19.190.15
    uplinks:
      - 25
      - 26
      - 35
      - 36
    spine_port_towards_leaf: Et4/3/1
    ports:
      - id: 32
        description: CIS-iSCSI
        type: vlan
        ip: 172.19.96.100/23
      - id: 1/1
        description: ->hec15f00501,e4a via MPO
        po: 10
      - id: 25/1
        description: sw-hec01-shs-01b, Et25
        po: 42
      - id: 26/1
        description: sw-hec01-shs-01b, Et26
        po: 42
    port_channels:
      - id: 10
        description: hec01f00501
        trunk: 30,32,40,50,55,130,2001-2499
  - number: 1b
    snmp:
      location: foo
      contact: bar
    oob_ip: 10.178.136.15
    nwmgmt_ip: 198.19.190.15
    uplinks:
      - 25
      - 26
      - 35
      - 36
    spine_port_towards_leaf: Et4/4/1
    ports:
      - id: 32
        description: CIS-iSCSI
        type: vlan
        ip: 172.19.96.101/23
      - id: 1/1
        description: ->hec15f00501,e4a via MPO
        po: 10
      - id: 25/1
        description: sw-hec01-shs-01a, Et25
        po: 42
      - id: 26/1
        description: sw-hec01-shs-01a, Et26
        po: 42
    port_channels:
      - id: 10
        description: hec01f00501
        trunk: 30,32,40,50,55,130,2001-2499
