---
  customers:
    - id: 7
      name: AMO
      backup:
        - 100.104.12.0/24
        - 100.104.91.0/24
    - id: 9
      name: TVI
      backup: ['100.66.108.0/24']
    - id: 11
      name: STD
      backup: ['100.66.57.0/24', '100.66.60.0/24', '100.66.61.0/24']
    - id: 13
      name: MEW
      backup: []
    - id: 15
      name: MCA
      backup: []
    - id: 20
      name: SIB
      backup: []
    - id: 24
      name: GID
      backup: []
    - id: 25
      name: THC
      backup: []
    - id: 26
      name: MDM
      backup: []
    - id: 28
      name: CSR
      backup: []
    - id: 29
      name: BNT
      backup: []
    - id: 32
      name: KAS
      backup: []
    - id: 34
      name: MVB
      backup: []
    - id: 36
      name: APG
      backup: []
    - id: 37
      name: WAK
      backup: []
    - id: 38
      name: PPG
      backup: []
    - id: 39
      name: FOD
      backup: []
    - id: 40
      name: XY4
      backup: []
    - id: 41
      name: VEN
      backup: []
    - id: 43
      name: ASB
      backup: []
    - id: 44
      name: XY5
      backup: []
    - id: 45
      name: IDO
      backup: []
    - id: 46
      name: NTT
      backup: []
    - id: 47
      name: JBO
      backup: []
    - id: 48
      name: IKE
      backup: []
    - id: 49
      name: SCL
      backup: []
    - id: 50
      name: GVS
      backup: []
    - id: 51
      name: WRL
      backup: []
    - id: 55
      name: NOK
      backup: []
    - id: 58
      name: BBC
      backup: []
    - id: 59
      name: SBB
      backup: []
    - id: 60
      name: GAV
      backup: []
    - id: 61
      name: AMM
      backup: []
    - id: 62
      name: CIM
      backup: []
    - id: 63
      name: JDW
      backup: []
    - id: 64
      name: AVL
      backup: []
    - id: 65
      name: HAI
      backup: []
    - id: 66
      name: NOB
      backup: []
    - id: 67
      name: ARL
      backup: []
    - id: 68
      name: KOF
      backup: []
    - id: 69
      name: INO
      backup: []
    - id: 70
      name: CHV
      backup: []
    - id: 71
      name: TUS
      backup: []
    - id: 72
      name: ADP
      backup: []
    - id: 74
      name: VEL
      backup: []
    - id: 75
      name: AVL-2
      backup: []
    - id: 76
      name: ETL
      backup: []
    - id: 77
      name: LPR
      backup: []
    - id: 78
      name: BLG
      backup: []
    - id: 79
      name: VKF
      backup: []
    - id: 80
      name: ALV
      backup: []
    - id: 82
      name: SUS
      backup: []
    - id: 83
      name: XY8
      backup: []
    - id: 84
      name: IFU
      backup: []
    - id: 85
      name: SHC
      backup: []
    - id: 86
      name: XS3
      backup: []
    - id: 87
      name: PRC
      backup: []
    - id: 454
      name: SFH
      backup: []
