# file: roles/cvp/tasks/main.yml
---
- name: "Gather CVP facts from {{inventory_hostname}}"
  arista.cvp.cv_facts:
  register: cvp_facts
  tags:
    - always

- name: Get status of CVP VM
  virt:
    command: "status"
    name: "{{ cvp.KvmDomain }}"
  register: vm_status
  tags:
    - cvp_stop

- name: Stop CVP VM if running
  virt:
    state: "shutdown"
    name: "{{ cvp.KvmDomain }}"
  when: vm_status.status == "running" or vm_status.status == "paused"
  tags:
    - cvp_stop

- name: Wait for VW to be shutdown
  virt:
    command: "status"
    name: "{{ cvp.KvmDomain }}"
  register: new_vm_status
  until: new_vm_status.status == "shutdown"
  retries: 10
  delay: 15
  tags:
    - cvp_stop

- name: Check if directory /data/cvp_old exists
  stat:
    path: '/data/cvp_old'
  register: cvp_old_dir
  tags:
    - cvp_stop

- name: Delete /data/cvp_old if exists
  file:
    state: absent
    path: '/data/cvp_old'
  when: cvp_old_dir.stat.exists and cvp_old_dir.stat.isdir
  tags:
    - cvp_stop

- name: Move current CVP to another directory (/data/cvp_old/)
  command: "mv /data/cvp /data/cvp_old"
  when: new_vm_status.status == "shutdown"
  tags:
    - cvp_stop

- name: Check that the cvp kvm file exists in {{ cvp.path_to_cvp_file }}
  delegate_to: 127.0.0.1
  stat:
    path: "{{ cvp.path_to_cvp_file }}{{ cvp.version }}"
  register: cvp_exists
  tags:
    - cvp_install

- name: CVP KVM file exists?
  debug:
    msg: "File exists: {{ cvp_exists.stat.exists }}"
  tags:
    - cvp_install

- name: Create directory for new CVP (/data/cvp/)
  command: "mkdir /data/cvp"
  args:
    warn: no
  when: cvp_exists.stat.exists == True
  tags:
    - cvp_install

- name: Copy CVP KVM file to CVA (this might take some time)
  copy:
    src: "{{ cvp.path_to_cvp_file }}{{ cvp.version }}"
    dest: "/data/cvp/{{ cvp.version }}"
    owner: root
    group: root
    mode: 0755
  when: cvp_exists.stat.exists == True
  tags:
    - cvp_install

- name: Unzip the CVP KVM file on the CVA
  command: "tar -zxvf /data/cvp/{{ cvp.version }} -C /data/cvp"
  args:
    warn: no
  tags:
    - cvp_install

- name: Find name of old disk 1
  find:
    paths: /data/cvp_old
    file_type: file
    patterns: '*disk1*'
  register: disk1_old
  tags:
    - cvp_install

- name: Find name of old disk 2
  find:
    paths: /data/cvp_old
    file_type: file
    patterns: '*disk2*'
  register: disk2_old
  tags:
    - cvp_install

- name: Find name of new disk 1
  find:
    paths: /data/cvp
    file_type: file
    patterns: '*disk1*'
  register: disk1_new
  tags:
    - cvp_install

- name: Find name of new disk 2
  find:
    paths: /data/cvp
    file_type: file
    patterns: '*disk2*'
  register: disk2_new
  tags:
    - cvp_install

- name: Rename the new disk 1 the same as the old disk 1 was named
  command: "mv /data/cvp/{{ disk1_new.files[0].path | regex_replace('.*cvp/(.*)', '\\1') }} /data/cvp/{{ disk1_old.files[0].path | regex_replace('.*cvp_old/(.*)', '\\1') }}"
  ignore_errors: yes
  args:
    warn: no
  tags:
    - cvp_install

- name: Rename the new disk 2 the same as the old disk 2 was named
  command: "mv /data/cvp/{{ disk2_new.files[0].path | regex_replace('.*cvp/(.*)', '\\1') }} /data/cvp/{{ disk2_old.files[0].path | regex_replace('.*cvp_old/(.*)', '\\1') }}"
  ignore_errors: yes
  args:
    warn: no
  tags:
    - cvp_install

- name: Copy old cvp.xml VM definition file to /data/cvp folder
  command: "cp /data/cvp_old/cvp.xml /data/cvp/cvp.xml"
  args:
    warn: no
  tags:
    - cvp_install

- name: Start new CVP VM
  virt:
    state: "running"
    name: "{{ cvp.KvmDomain }}"
  tags:
    - cvp_install

- name: Render and create YAML File
  delegate_to: 127.0.0.1
  template:
    src: "templates/singlenode.j2"
    dest: "{{role_path}}/files/singlenode.yaml"
  tags:
    - cvp_init

- name: Copy YAML File to CVA
  copy:
    src: "{{role_path}}/files/singlenode.yaml"
    dest: /tmp/singlenode.yaml
    owner: root
    group: root
    mode: 0755
  tags:
    - cvp_init

- name: Copy cvpConfigParser.py to CVA
  copy:
    src: "{{role_path}}/files/cvpConfigParser.py"
    dest: /tmp/cvpConfigParser.py
    owner: root
    group: root
    mode: 0755
  tags:
    - cvp_init

- name: Copy geniso.py to CVA
  copy:
    src: "{{role_path}}/files/geniso.py"
    dest: /tmp/geniso.py
    owner: root
    group: root
    mode: 0755
  tags:
    - cvp_init

- name: Copy setuptools to CVA
  copy:
    src: "{{role_path}}/files/setuptools-41.0.1.tar.gz"
    dest: /tmp/setuptools-41.0.1.tar.gz
    owner: root
    group: root
    mode: 0755
  tags:
    - cvp_init

- name: Unzip setuptools
  command: "tar -zxvf /tmp/setuptools-41.0.1.tar.gz -C /tmp"
  tags:
    - cvp_init

#- name: Extract setuptools to CVA
#  unarchive:
#    src: "{{role_path}}/files/setuptools-41.0.1.zip"
#    dest: /tmp/
#  tags:
#    - cvp_init

- name: Build setuptools
  command: "python /tmp/setuptools-41.0.1/setup.py build"
  tags:
    - cvp_init

- name: Install setuptools
  command: "python /tmp/setuptools-41.0.1/setup.py install"
  tags:
    - cvp_init

- name: Copy setuptools folder to python libs
  command: "cp -r /tmp/setuptools-41.0.1/. /usr/lib/python2.7/site-packages/"
  tags:
    - cvp_init

- name: Extract pip to CVA
  unarchive:
    src: "{{role_path}}/files/pip-19.1.1.tar.gz"
    dest: /tmp/
  tags:
    - cvp_init

- name: Install pip
  shell: python setup.py install
  args:
    chdir: /tmp/pip-19.1.1/
  tags:
    - cvp_init

- name: Copy PyYAML-5.1.tar.gz to CVA
  copy:
    src: "{{role_path}}/files/PyYAML-5.1.tar.gz"
    dest: /tmp/PyYAML-5.1.tar.gz
    owner: root
    group: root
    mode: 0755
  tags:
    - cvp_init

- name: Install PyYaml
  command: "pip install /tmp/PyYAML-5.1.tar.gz"
  tags:
    - cvp_init

- name: Generate ISO file
  command: "/tmp/geniso.py -y /tmp/singlenode.yaml -p {{ cvp.password }} -o /tmp"
  tags:
    - cvp_init

- name: Start cvp VM if not running
  command: "virsh start {{ cvp.KvmDomain }}"
  ignore_errors: yes
  tags:
    - cvp_init

- name: Attach the cdrom to the cvp VM
  command: "virsh attach-disk {{ cvp.KvmDomain }} /tmp/node1-{{ cvp.vmname }}.iso  hdc --type cdrom --mode readonly"
  tags:
    - cvp_init

- name: Reboot cvp VM with the cdrom infos
  command: "virsh reboot {{ cvp.KvmDomain }}"
  tags:
    - cvp_init

# Pause for 720 seconds to power up vm
- pause:
    seconds: 720
  tags:
    - cvp_init

- name: Render CVP routes and put the file to the CVP machine
  delegate_to: "{{ cvp.ip_eth0 }}"
  template:
    src: "templates/route-eth1.j2"
    dest: "/etc/sysconfig/network-scripts/route-eth1"
  tags:
    - cvp_init

- name: Restart network service
  delegate_to: "{{ cvp.ip_eth0 }}"
  service:
    name: network
    state: restarted
  tags:
    - cvp_init

- name: Render DHCP config and put the file to the CVP machine
  delegate_to: "{{ cvp.ip_eth0 }}"
  template:
    src: "templates/dhcpd.conf.j2"
    dest: "/etc/dhcp/dhcpd.conf"
  tags:
    - cvp_init

- name: Set the dhcpd to enabled for persistence after reboot
  delegate_to: "{{ cvp.ip_eth0 }}"
  command: "systemctl enable dhcpd"
  tags:
    - cvp_init

- name: Restart dhcp service
  delegate_to: "{{ cvp.ip_eth0 }}"
  service:
    name: dhcpd
    state: restarted
  tags:
    - cvp_init

- name: "Create backup user account and add user to group cvp"
  delegate_to: "{{ cvp.ip_eth0 }}"
  user:
    name: "{{ cvp.backupuser }}"
    groups: "cvp"
  tags:
    - cvp_init

- name: "Add authorized keys"
  delegate_to: "{{ cvp.ip_eth0 }}"
  authorized_key:
    user: "{{ cvp.backupuser }}"
    key: "{{ lookup('file', '{{role_path}}/files/'+ cvp.backupuser + '.key.pub') }}"
  tags:
    - cvp_init

- name: Reset cvpadmin password
  delegate_to: "{{ cvp.ip_eth0 }}"
  command: "/cvpi/tools/update-mgmt-password -auth none -password {{ cvp.password }}"
  tags:
    - cvp_init

- name: Check if directory for configlet builders exists
  delegate_to: 127.0.0.1
  stat:
    path: '{{role_path}}/files/configlet_builders'
  register: dir_to_delete
  tags:
    - configlets

- name: Delete {{role_path}}/files/configlet_builders if exists
  delegate_to: 127.0.0.1
  file:
    state: absent
    path: '{{role_path}}/files/configlet_builders'
  when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir
  tags:
    - configlets

- name: Create directory for configlet_builders again
  delegate_to: 127.0.0.1
  file:
    state: directory
    path: '{{role_path}}/files/configlet_builders'
  when: dir_to_delete is defined or dir_to_delete.stat.exist == False
  tags:
    - configlets

- name: Check if directory for configs exists
  delegate_to: 127.0.0.1
  stat:
    path: '{{role_path}}/files/configs'
  register: dir_to_delete
  tags:
    - configlets

- name: Delete {{role_path}}/files/configs if exists
  delegate_to: 127.0.0.1
  file:
    state: absent
    path: '{{role_path}}/files/configs'
  when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir
  tags:
    - configlets

- name: Create directory for configs again
  delegate_to: 127.0.0.1
  file:
    state: directory
    path: '{{role_path}}/files/configs'
  when: dir_to_delete is defined or dir_to_delete.stat.exist == False
  tags:
    - configlets

- name: Render all templates
  delegate_to: 127.0.0.1
  template:
    src: "templates/config_templates/{{item}}.j2"
    dest: "{{role_path}}/files/configs/{{item}}"
  loop:
    - sw-hec
    - sw-hec-aaa
    - sw-hec-snmp
    - sw-hec-fab-snmp
    - sw-hec-switch-snmp
    - sw-hec-ntp
    - sw-hec-fab-ntp
    - sw-hec-switch-ntp
    - sw-hec-logging
    - sw-hec-fab-logging
    - sw-hec-switch-logging
    - sw-hec-fab-L900
    - sw-hec-oob-vrf
    - sw-hec-tele-oob
    - HEC-IPMI
    - sw-hec-oob-common
    - sw-hec-tele-default
    - HEC-VLANs
    - hec-hana
    - sw-hec-leaf
    - hec-vmware
    - hec-xen
    - sw-hec-spine
    - sw-hec-hana-7160-32CQ
    - sw-hec-hvv-7160-32CQ
    - sw-hec-hvx-7160-32CQ
    - sw-hec-hvx-7160-48YC6
    - sw-hec-oob-01
    - sw-hec-oob-01a
    - sw-hec-oob-01b
    - sw-mlag-a
    - sw-mlag-b
    - mgmt-oob
    - mgmt-default
    - CVP-Arista
  tags:
    - configlets

- name: Render all configlet_builder templates
  delegate_to: 127.0.0.1
  template:
    src: "templates/config_templates/{{item}}.j2"
    dest: "{{role_path}}/files/configlet_builders/{{item}}"
  loop:
    - sw-hec-autoconf
    - sw-hec-autoconf-ipmi
    - sw-hec-descriptions
    - sw-hec-descriptions-hvv
  tags:
    - configlets

- name: Render sw-hecxx-spine-xx
  delegate_to: 127.0.0.1
  template:
    src: "templates/config_templates/sw-hec-spine-xx.j2"
    dest: "{{role_path}}/files/configs/sw-hec-spine-{{ item }}"
  with_items: "{{ hec.spine_nr }}"
  tags:
    - configlets

- name: Render sw-hecxx-oob-xx
  delegate_to: 127.0.0.1
  template:
    src: "templates/config_templates/sw-hec-oob-xx.j2"
    dest: "{{role_path}}/files/configs/sw-hec-oob-0{{ item.number }}"
  with_items: "{{ hec.oobs_2_7 }}"
  tags:
    - configlets

- set_fact:
    id: 'b1a'
  tags:
    - configlets
    - borderleafs

- name: Render sw-hec-brdr-01a
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/hec_sw_borderleaf.j2
    dest: "{{role_path}}/files/configs/sw-hec-brdr-01a"
  tags:
    - configlets
    - borderleafs

- set_fact:
    id: 'b1b'
  tags:
    - configlets
    - borderleafs

- name: Render sw-hec-brdr-01b
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/hec_sw_borderleaf.j2
    dest: "{{role_path}}/files/configs/sw-hec-brdr-01b"
  tags:
    - configlets
    - borderleafs

- set_fact:
    id: 'b2a'
  tags:
    - configlets
    - borderleafs

- name: Render sw-hec-brdr-02a
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/hec_sw_borderleaf.j2
    dest: "{{role_path}}/files/configs/sw-hec-brdr-02a"
  tags:
    - configlets
    - borderleafs

- set_fact:
    id: 'b2b'
  tags:
    - configlets
    - borderleafs

- name: Render sw-hec-brdr-02b
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/hec_sw_borderleaf.j2
    dest: "{{role_path}}/files/configs/sw-hec-brdr-02b"
  tags:
    - configlets
    - borderleafs

- set_fact:
    id: 'b3a'
  tags:
    - configlets
    - borderleafs

- name: Render sw-hec-brdr-03a
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/hec_sw_borderleaf.j2
    dest: "{{role_path}}/files/configs/sw-hec-brdr-03a"
  tags:
    - configlets
    - borderleafs

- set_fact:
    id: 'b3b'
  tags:
    - configlets
    - borderleafs

- name: Render sw-hec-brdr-03b
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/hec_sw_borderleaf.j2
    dest: "{{role_path}}/files/configs/sw-hec-brdr-03b"
  tags:
    - configlets
    - borderleafs

- set_fact:
    id: 's1a'
  tags:
    - configlets
    - storageleafs

- name: Render sw-hec-str-01a
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/hec_sw_borderleaf.j2
    dest: "{{role_path}}/files/configs/sw-hec-str-01a"
  tags:
    - configlets
    - storageleafs

- set_fact:
    id: 's1b'
  tags:
    - configlets
    - storageleafs

- name: Render sw-hec-str-01b
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/hec_sw_borderleaf.j2
    dest: "{{role_path}}/files/configs/sw-hec-str-01b"
  tags:
    - configlets
    - storageleafs

- name: Copy configlet builders to the CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/configlet_builders"
    dest: /tmp
  tags:
    - upload_configlets

- name: Copy configlets to the CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/configs"
    dest: /tmp
  tags:
    - upload_configlets

- name: Copy python upload script for configlet builders to CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/configlet_builder.py"
    dest: /tmp/configlet_builder.py
  tags:
    - upload_configlets

- name: Copy python upload script for configlets to CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/configlets.py"
    dest: /tmp/configlets.py
  tags:
    - upload_configlets

- name: Copy cvprac to /tmp/cvprac/ direcory on CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/cvprac"
    dest: /tmp
  tags:
    - reload_TerminAttr
    - upload_configlets

- name: Upload generated configlet builders
  delegate_to: "{{ cvp.ip_eth0 }}"
  command: python /tmp/configlet_builder.py "/tmp/configlet_builders/" "{{ cvp.ip_eth0 }}" "{{ cvp.password }}"
  tags:
    - upload_configlets

- name: "Upload configlets to {{inventory_hostname}} instance"
  arista.cvp.cv_configlet:
    cvp_facts: "{{ cvp_facts.ansible_facts }}"
    configlets: "{{ configlet_list }}"
    state: present
  register: cvp_configlet
  tags:
    - upload_configlets

- name: "Build Container topology on {{inventory_hostname}} and assign configlets"
  arista.cvp.cv_container:
    topology: "{{container}}"
    cvp_facts: "{{cvp_facts.ansible_facts}}"
    mode: merge
  tags:
    - create_containers
    - configlets_assign

- name: Copy aaa server creation script to CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/aaa_configuration.py"
    dest: /tmp/aaa_configuration.py
  tags:
    - configure_aaa

- name: Configure AAA servers
  delegate_to: "{{ cvp.ip_eth0 }}"
  command: python /tmp/aaa_configuration.py "{{ cvp.aaa_config }}" "{{ cvp.ip_eth0 }}" "{{ cvp.password }}"
  tags:
    - configure_aaa

- name: Copy restore_reload_TerminAttr.py to CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/restore_reload_TerminAttr.py"
    dest: /tmp/restore_reload_TerminAttr.py
  tags:
    - reload_TerminAttr

- name: Reload TerminAttr on devices after restoring a backup
  delegate_to: "{{ cvp.ip_eth0 }}"
  command: "python /tmp/restore_reload_TerminAttr.py {{ cvp.ip_eth0 }} {{ cvp.password }}"
  tags:
    - reload_TerminAttr
