# file: roles/cvp/tasks/main.yml
---
- name: "Gather CVP facts from {{inventory_hostname}}"
  arista.cvp.cv_facts:
  register: cvp_facts
  tags:
    - upload_configlets
    - create_containers
    - configlets_assign
    - delete_configlets
    - configure_aaa
    - reload_TerminAttr

# start work on configlet (static and dynamic builders), containers
#  and maintain them on the cvp server itself
- name: Check if directory for configlet builders exists
  delegate_to: 127.0.0.1
  stat:
    path: '{{role_path}}/files/configlet_builders'
  register: dir_to_delete
  tags:
    - configlets

- name: Delete {{role_path}}/files/configlet_builders if exists
  delegate_to: 127.0.0.1
  file:
    state: absent
    path: '{{role_path}}/files/configlet_builders'
  when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir
  tags:
    - configlets

- name: Create directory for configlet_builders again
  delegate_to: 127.0.0.1
  file:
    state: directory
    path: '{{role_path}}/files/configlet_builders'
  when: dir_to_delete is defined or dir_to_delete.stat.exist == False
  tags:
    - configlets

- name: Check if directory for configs exists
  delegate_to: 127.0.0.1
  stat:
    path: '{{role_path}}/files/configs'
  register: dir_to_delete
  tags:
    - configlets

- name: Delete {{role_path}}/files/configs if exists
  delegate_to: 127.0.0.1
  file:
    state: absent
    path: '{{role_path}}/files/configs'
  when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir
  tags:
    - configlets

- name: Create directory for configs again
  delegate_to: 127.0.0.1
  file:
    state: directory
    path: '{{role_path}}/files/configs'
  when: dir_to_delete is defined or dir_to_delete.stat.exist == False
  tags:
    - configlets

- name: Grab Spine interfaces
  delegate_to: 127.0.0.1
  connection: network_cli
  eos_facts:
    host: "{{ hec.oob_prefix }}.11"
    gather_subset: min
    gather_network_resources: interfaces
  ignore_errors: yes
  ignore_unreachable: yes
  tags:
    - configlets

- name: Store the Spine interfaces in a file
  delegate_to: 127.0.0.1
  copy:
    content: '{{ansible_network_resources | to_nice_yaml}}'
    dest: '{{role_path}}/files/configs/spine_interfaces'
  ignore_errors: yes
  ignore_unreachable: yes
  tags:
    - configlets

- name: Include interface for Spine from file
  delegate_to: 127.0.0.1
  include_vars:
    file: '{{role_path}}/files/configs/spine_interfaces'
    name: spine_interfaces
  ignore_errors: yes
  ignore_unreachable: yes
  tags:
    - configlets

- name: Render all templates
  delegate_to: 127.0.0.1
  template:
    src: "templates/config_templates/{{item}}.j2"
    dest: "{{role_path}}/files/configs/{{item}}"
  loop:
    - sw-hec
    - sw-hec-aaa
    - sw-hec-snmp
    - sw-hec-fab-snmp
    - sw-hec-switch-snmp
    - sw-hec-ntp
    - sw-hec-fab-ntp
    - sw-hec-switch-ntp
    - sw-hec-logging
    - sw-hec-fab-logging
    - sw-hec-switch-logging
    - sw-hec-fab-L900
    - sw-hec-oob-vrf
    - sw-hec-tele-oob
    - HEC-IPMI
    - sw-hec-oob-common
    - sw-hec-tele-default
    - HEC-VLANs
    - hec-hana
    - sw-hec-leaf
    - hec-vmware
    - hec-vmware-L2
    - hec-xen
    - sw-hec-spine
    - sw-hec-hana-7160-32CQ
    - sw-hec-hana-pwr-7160-32CQ
    - sw-hec-hvv-7160-32CQ
    - sw-hec-vmware-7150S-64-CL
    - sw-hec-hvx-7160-32CQ
    - sw-hec-hvx-7160-48YC6
    - sw-hec-oob-01
    - sw-hec-oob-01a
    - sw-hec-oob-01b
    - sw-mlag-a
    - sw-mlag-b
    - mgmt-oob
    - mgmt-default
    - CVP-Arista
    - sw-hec-vtep
    - hec-shs
    - sw-hec-hana-pwr
    - autoconf.ini
    - hec_sw_leaf_individual
    - hec_sw_leaf_pair
    - 7160-profile-tcam-acl
  tags:
    - configlets

# next task is to reuse the sw-hec-aaa.j2 template but generate the hana-specific radius strings.
- set_fact:
    aaa_purpose: 'hana'
  tags:
    - configlets

- name: Render hana aaa configlet template
  delegate_to: 127.0.0.1
  template:
    src: "templates/config_templates/sw-hec-aaa.j2"
    dest: "{{role_path}}/files/configs/{{item}}"
  loop:
    - sw-hec-aaa-hana
  tags:
    - configlets

- name: Render all configlet_builder templates
  delegate_to: 127.0.0.1
  template:
    src: "templates/config_templates/{{item}}.j2"
    dest: "{{role_path}}/files/configlet_builders/{{item}}"
  loop:
    - sw-hec-autoconf
    - sw-hec-autoconf-ipmi
    - sw-hec-descriptions
    - sw-hec-descriptions-hvv
    - sw-hec-autoconf-generate-only
  tags:
    - configlets

- name: Render sw-hecxx-spine-xx
  delegate_to: 127.0.0.1
  template:
    src: "templates/config_templates/sw-hec-spine-xx.j2"
    dest: "{{role_path}}/files/configs/sw-hec-spine-{{ item.id }}"
  with_items: "{{ hec.spine.number }}"
  tags:
    - configlets

- name: Render sw-hecxx-superspine-xx
  delegate_to: 127.0.0.1
  template:
    src: "templates/config_templates/sw-hec-superspine-xx.j2"
    dest: "{{role_path}}/files/configs/sw-hec-superspine-{{ item.id }}"
  with_items: "{{ hec.superspine.number }}"
  when: hec.superspine|default("") != ""
  tags:
    - configlets
    - superspines

- name: Render sw-hecxx-oob-xx
  delegate_to: 127.0.0.1
  template:
    src: "templates/config_templates/sw-hec-oob-xx.j2"
    dest: "{{role_path}}/files/configs/sw-hec-oob-0{{ item.number }}"
  with_items: "{{ hec.oobs_2_7 }}"
  tags:
    - configlets

- set_fact:
    id: 'b'
  tags:
    - configlets
    - borderleafs

- name: "Render Borderleafs"
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/hec_sw_borderleaf.j2
    dest: "{{role_path}}/files/configs/sw-hec-brdr-{%if item.number is match('^[1-9][a-z]$') %}0{% endif %}{{item.number}}"
  loop: '{{ hec.brdr }}'
  tags:
    - configlets
    - borderleafs

- set_fact:
    id: 's'
  tags:
    - configlets
    - storageleafs

- name: "Render Storageleafs"
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/hec_sw_borderleaf.j2
    dest: "{{role_path}}/files/configs/sw-hec-str-{%if item.number is match('^[1-9][a-z]$') %}0{% endif %}{{item.number}}"
  loop: '{{ hec.str }}'
  tags:
    - configlets
    - storageleafs

- set_fact:
    id: 's'
  tags:
    - configlets
    - storageleafs

- name: "Render Shared Hana Storageleafs"
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/hec_sw_borderleaf.j2
    dest: "{{role_path}}/files/configs/sw-hec-shs-{%if item.number is match('^[1-9][a-z]$') %}0{% endif %}{{item.number}}"
  loop: '{{ hec.shs }}'
  tags:
    - configlets
    - storageleafs

- set_fact:
    id: '01'
  tags:
    - configlets
    - interdc

- name: Render sw-hec-interdc
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/sw-hec-interdc.j2
    dest: "{{role_path}}/files/configs/sw-hec-interdc01"
  tags:
    - configlets
    - interdc

- set_fact:
    id: '02'
  tags:
    - configlets
    - interdc

- name: Render sw-hec-interdc
  delegate_to: 127.0.0.1
  template:
    src: templates/config_templates/sw-hec-interdc.j2
    dest: "{{role_path}}/files/configs/sw-hec-interdc02"
  tags:
    - configlets
    - interdc

- name: Copy configlet builders to the CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/configlet_builders/"
    dest: tmp
  tags:
    - upload_configlets

- name: Copy configlets to the CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/configs"
    dest: tmp
  tags:
    - upload_configlets

- name: Copy python upload script for configlet builders to CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/configlet_builder.py"
    dest: tmp/configlet_builder.py
  tags:
    - upload_configlets

- name: Copy python upload script for configlets to CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/configlets.py"
    dest: tmp/configlets.py
  tags:
    - upload_configlets

- name: Copy cvprac to tmp/cvprac/ direcory on CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/cvprac"
    dest: tmp
  tags:
    - reload_TerminAttr
    - upload_configlets

- name: Upload generated configlet builders
  delegate_to: "{{ cvp.ip_eth0 }}"
  command: python tmp/configlet_builder.py "{{role_path}}/files/configlet_builders/" "{{ cvp.ip_eth0 }}" "{{ cvp.password }}"
  tags:
    - upload_configlets

- name: "Upload configlets to {{inventory_hostname}} instance"
  arista.cvp.cv_configlet:
    cvp_facts: "{{ cvp_facts.ansible_facts }}"
    configlets: "{{ configlet_list }}"
    configlet_filter: "{{ configlet_filter_list_generic }}"
    state: present
  register: cvp_configlet
  tags:
    - upload_configlets

- name: "Build Container topology on {{inventory_hostname}} and assign configlets"
  arista.cvp.cv_container:
    topology: "{{container}}"
    cvp_facts: "{{cvp_facts.ansible_facts}}"
    mode: merge
  tags:
    - create_containers
    - configlets_assign

- name: "Delete all defined configlets from {{inventory_hostname}} instance"
  arista.cvp.cv_configlet:
    cvp_facts: "{{ cvp_facts.ansible_facts }}"
    configlets: "{{ configlet_list }}"
    configlet_filter: "{{ configlet_filter_list_generic }}"
    state: absent
  register: cvp_configlet
  tags:
    - delete_configlets

- name: "Delete all defined containers from {{inventory_hostname}}"
  arista.cvp.cv_container:
    topology: "{{container}}"
    cvp_facts: "{{cvp_facts.ansible_facts}}"
    mode: delete
  tags:
    - delete_containers

- name: Copy aaa server creation script to CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/aaa_configuration.py"
    dest: tmp/aaa_configuration.py
  tags:
    - configure_aaa

- name: Configure AAA servers
  delegate_to: "{{ cvp.ip_eth0 }}"
  command: python tmp/aaa_configuration.py "{{ cvp.aaa_config }}" "{{ cvp.ip_eth0 }}" "{{ cvp.password }}"
  tags:
    - configure_aaa

- name: Copy restore_reload_TerminAttr.py to CVP
  delegate_to: "{{ cvp.ip_eth0 }}"
  copy:
    src: "{{role_path}}/files/restore_reload_TerminAttr.py"
    dest: tmp/restore_reload_TerminAttr.py
  tags:
    - reload_TerminAttr

- name: Reload TerminAttr on devices after restoring a backup
  delegate_to: "{{ cvp.ip_eth0 }}"
  command: "python tmp/restore_reload_TerminAttr.py {{ cvp.ip_eth0 }} {{ cvp.password }}"
  tags:
    - reload_TerminAttr

- name: dummy task to test dependencies
  debug:
    msg: "{{ mapping }}" # this should come from repo_hec_globals default variables
  tags:
    - test_deps
